# Linear Regression Baseline — Heat Pump Load Forecasting

Simple baseline: aggregate 5-minute telemetry to daily averages per device, train linear regression to predict daily avg x2, then generate monthly predictions for submission.

In [1]:
import pandas as pd
import numpy as np


DATA_PATH = "data/data.csv"
CHUNK_SIZE = 500_000

FEATURE_COLS = [
    "t1", "t2", "t3", "t4", "t5", "t6", "t7",
    "t8", "t9", "t10", "t11", "t12", "t13",
    "x1", "x3", "deviceType",
]
TARGET_COL = "x2"
ALL_COLS = FEATURE_COLS + [TARGET_COL]

print("Imports OK")

Imports OK

## Cell 2 — Chunked load & daily aggregation (train only)

In [2]:
train_sums = []
train_counts = []

for i, chunk in enumerate(pd.read_csv(DATA_PATH, chunksize=CHUNK_SIZE, low_memory=False)):
    # Filter train only
    chunk = chunk[chunk["period"] == "train"].copy()
    if len(chunk) == 0:
        continue

    # Parse timedate and extract date
    chunk["timedate"] = pd.to_datetime(
        chunk["timedate"].str.replace(" UTC", "", regex=False), utc=True
    )
    chunk["date"] = chunk["timedate"].dt.date

    # Only keep columns we need
    cols_present = [c for c in ALL_COLS if c in chunk.columns]
    grp = chunk.groupby(["deviceId", "date"])[cols_present]

    train_sums.append(grp.sum())
    train_counts.append(grp.count())

    if (i + 1) % 5 == 0:
        print(f"  processed {(i + 1) * CHUNK_SIZE:,} rows...")

print("Combining partial aggregations...")
total_sum = pd.concat(train_sums).groupby(level=["deviceId", "date"]).sum()
total_count = pd.concat(train_counts).groupby(level=["deviceId", "date"]).sum()
daily_train = (total_sum / total_count).reset_index()

del train_sums, train_counts, total_sum, total_count

print(f"Daily train aggregation complete: {daily_train.shape}")

  processed 2,500,000 rows...
  processed 5,000,000 rows...
  processed 7,500,000 rows...
  processed 10,000,000 rows...
  processed 12,500,000 rows...
  processed 15,000,000 rows...
  processed 17,500,000 rows...
  processed 20,000,000 rows...
  processed 22,500,000 rows...
  processed 25,000,000 rows...
  processed 27,500,000 rows...
  processed 30,000,000 rows...
  processed 32,500,000 rows...
  processed 35,000,000 rows...
  processed 37,500,000 rows...
  processed 40,000,000 rows...
  processed 42,500,000 rows...
  processed 45,000,000 rows...
  processed 47,500,000 rows...
  processed 50,000,000 rows...
  processed 52,500,000 rows...
  processed 55,000,000 rows...
  processed 57,500,000 rows...
  processed 60,000,000 rows...
  processed 62,500,000 rows...
Combining partial aggregations...
Daily train aggregation complete: (122310, 19)

In [10]:
daily_train.describe().T

,count,mean,std,min,25%,50%,75%,max
t1,122310.0,2.803913e-01,0.032390,0.000000,0.260833,0.276701,0.297535,1.000000
t2,122310.0,4.533377e-02,0.005849,0.030000,0.040000,0.046021,0.050000,0.160000
t3,122310.0,4.680033e-03,0.062619,0.000000,0.000000,0.000000,0.000000,1.000000
t4,122310.0,3.914938e-01,0.047530,0.000000,0.363507,0.387482,0.418750,1.000000
t5,122310.0,4.354056e-01,0.037649,0.250000,0.415208,0.436944,0.458507,1.000000
t6,122310.0,4.155492e-01,0.032826,0.249340,0.398368,0.418750,0.437150,1.000000
t7,122310.0,2.104008e-01,0.034406,0.110069,0.203229,0.208229,0.213264,0.473333
t8,122310.0,5.142527e-01,0.021561,0.400000,0.499792,0.514896,0.529236,0.580625
t9,122310.0,3.911278e-01,0.068621,0.000000,0.365035,0.388333,0.408630,0.900000
t10,122310.0,2.065640e-01,0.004190,0.180000,0.202361,0.207396,0.210000,0.220833
t11,122310.0,2.054771e-01,0.003829,0.180000,0.201944,0.205313,0.208819,0.220000
t12,122310.0,6.439306e-02,0.005213,0.040000,0.061250,0.065000,0.068380,0.150000
t13,122310.0,6.697683e-02,0.005810,0.040000,0.063785,0.067465,0.070250,0.150000
x1,122310.0,2.668538e-08,0.000004,0.000000,0.000000,0.000000,0.000000,0.001076
x3,122310.0,7.291718e+00,1.664340,1.000000,7.000000,8.000000,9.000000,9.000000
deviceType,122310.0,1.289891e+01,4.048539,7.000000,11.000000,11.000000,19.000000,19.000000
x2,122310.0,1.577515e-01,0.152877,0.000000,0.057503,0.115302,0.198147,0.980518

## Cell 3 — Inspect daily aggregated dataframe

In [3]:
print(f"Shape: {daily_train.shape}")
print(f"\nNull counts:")
print(daily_train.isnull().sum())
print(f"\nUnique (deviceId, date) pairs: {daily_train[['deviceId', 'date']].drop_duplicates().shape[0]}")
daily_train.head()

Shape: (122310, 19)

Null counts:
deviceId      0
date          0
t1            0
t2            0
t3            0
t4            0
t5            0
t6            0
t7            0
t8            0
t9            0
t10           0
t11           0
t12           0
t13           0
x1            0
x3            0
deviceType    0
x2            0
dtype: int64

Unique (deviceId, date) pairs: 122310

,deviceId,date,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,x1,x3,deviceType,x2
0,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-01,0.307118,0.050000,0.0,0.393854,0.442396,0.431250,0.206076,0.507778,0.382951,0.210833,0.209028,0.066771,0.068333,0.0,8.0,19.0,0.102980
1,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-02,0.307639,0.050000,0.0,0.387778,0.446528,0.434444,0.207917,0.513368,0.386424,0.210000,0.209826,0.067604,0.069653,0.0,8.0,19.0,0.102154
2,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-03,0.303993,0.050000,0.0,0.389236,0.448715,0.437569,0.206736,0.518056,0.390069,0.210000,0.209931,0.068750,0.070174,0.0,8.0,19.0,0.110116
3,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-04,0.300389,0.047845,0.0,0.398269,0.457951,0.444912,0.207244,0.520247,0.397350,0.210000,0.209929,0.069682,0.070389,0.0,8.0,19.0,0.123136
4,000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...,2024-10-05,0.300000,0.050000,0.0,0.398229,0.457431,0.444201,0.205833,0.523854,0.396215,0.210000,0.209826,0.069549,0.070139,0.0,8.0,19.0,0.129621

## Cell 4 — Train Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error

feature_cols_present = [c for c in FEATURE_COLS if c in daily_train.columns]

In [113]:
feature_cols_present = ['t1',
 't2',
 't3',
 't4',
 't5',
 't6',
 't7',
 't8',
 't9',
 't10',
 't11',
 't12',
 't13',
 'x1',
 'x3',
 'deviceType']

In [97]:
train_clean = daily_train.dropna(subset=feature_cols_present + [TARGET_COL])
X_train = train_clean[feature_cols_present].values
y_train = train_clean[TARGET_COL].values

model = LinearRegression()
model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
train_mae = mean_absolute_error(y_train, y_pred_train)
print(f"Train MAE (in-sample): {train_mae:.6f}")

print("\nCoefficients:")
for feat, coef in zip(feature_cols_present, model.coef_):
    print(f"  {feat:>12s}: {coef:.6f}")
print(f"  {'intercept':>12s}: {model.intercept_:.6f}")

Train MAE (in-sample): 0.054573

Coefficients:
            t1: -0.150867
            t2: -0.756628
            t3: 0.018848
            t4: 0.476504
            t5: 2.774909
            t6: -2.641620
            t7: 0.269315
            t8: 1.429245
            t9: 0.079012
           t10: -3.573991
           t11: -4.682080
           t12: -1.641452
           t13: 0.861022
            x1: -13.804253
            x3: 0.001452
    deviceType: 0.017310
     intercept: 0.629148

In [114]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# Dictionary to store a unique model for each device type
models_per_type = {}
train_info = []

unique_types = daily_train['deviceType'].unique()

for d_type in unique_types:
    # Filter data for this specific device type
    df_type = daily_train[daily_train['deviceType'] == d_type].dropna(subset=feature_cols_present + [TARGET_COL])

    if len(df_type) < 5:  # Minimum samples check
        print(f"Skipping Device Type {d_type}: Not enough data.")
        continue

    X_t = df_type[feature_cols_present].values
    y_t = df_type[TARGET_COL].values

    # Initialize and train standard Linear Regression
    model = LinearRegression()
    model.fit(X_t, y_t)

    # Store the model object
    models_per_type[d_type] = model

    # Calculate in-sample MAE for reporting
    y_p = model.predict(X_t)
    mae = mean_absolute_error(y_t, y_p)
    train_info.append({'Type': d_type, 'MAE': mae, 'Samples': len(df_type)})

# Display summary
print(f"{'Device Type':<15} | {'Train MAE':<12} | {'Sample Count'}")
print("-" * 45)
for info in train_info:
    print(f"{info['Type']:<15} | {info['MAE']:<12.6f} | {info['Samples']}")

Device Type     | Train MAE    | Sample Count
---------------------------------------------
19.0            | 0.090563     | 35154
11.0            | 0.019689     | 74912
7.0             | 0.008838     | 12244

In [69]:
train_clean["deviceType"].value_counts()

deviceType
11.0    74912
19.0    35154
7.0     12244
Name: count, dtype: int64

In [108]:
import optuna
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score

lasso_models = {}
lasso_best_alphas = {}

for d_type in daily_train['deviceType'].unique():
    # Filter data for this device
    df_type = daily_train[daily_train['deviceType'] == d_type].dropna(subset=feature_cols_present + [TARGET_COL])
    if len(df_type) < 20: continue # Skip if data is too sparse for CV

    X_t, y_t = df_type[feature_cols_present].values, df_type[TARGET_COL].values

    def objective(trial):
        # Search alpha on a log scale
        alpha = trial.suggest_float("alpha", 1e-5, 10.0, log=True)
        # We increase max_iter to ensure Lasso converges with small alphas
        model = Lasso(alpha=alpha, max_iter=5000, random_state=42)
        model.fit(X_t, y_t)
        # scoring is 'neg_mean_absolute_error' because we want to minimize MAE
        preds = model.predict(X_t)
        return mean_absolute_error(y_t, preds)

    print(f"Optimizing Lasso for Device: {d_type}")
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=300, show_progress_bar=False)

    # Train the final Lasso model for this device using the best alpha
    best_alpha = study.best_params['alpha']
    final_model = Lasso(alpha=best_alpha, max_iter=5000).fit(X_t, y_t)

    lasso_models[d_type] = final_model
    lasso_best_alphas[d_type] = best_alpha

print("\nBest Lasso Alphas found:", lasso_best_alphas)

[I 2026-03-14 19:58:45,249] A new study created in memory with name: no-name-3b35e0da-bd1d-418d-a6d2-4225d1346a82
[I 2026-03-14 19:58:45,252] Trial 0 finished with value: 0.1680971070540161 and parameters: {'alpha': 1.6422656647711475}. Best is trial 0 with value: 0.1680971070540161.
[I 2026-03-14 19:58:45,256] Trial 1 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.12894104473129148}. Best is trial 0 with value: 0.1680971070540161.
[I 2026-03-14 19:58:45,263] Trial 2 finished with value: 0.09195853631476762 and parameters: {'alpha': 2.6466461212041496e-05}. Best is trial 2 with value: 0.09195853631476762.
[I 2026-03-14 19:58:45,266] Trial 3 finished with value: 0.1680971070540161 and parameters: {'alpha': 1.405881015935189}. Best is trial 2 with value: 0.09195853631476762.
[I 2026-03-14 19:58:45,273] Trial 4 finished with value: 0.09108769015369172 and parameters: {'alpha': 1.1000152951517555e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,275] Trial 5 finished with value: 0.1680971070540161 and parameters: {'alpha': 1.789159468513292}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,278] Trial 6 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.43795260594794216}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,281] Trial 7 finished with value: 0.16752766321557244 and parameters: {'alpha': 0.015813445670728496}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,283] Trial 8 finished with value: 0.10517867943613776 and parameters: {'alpha': 0.00021776095391956782}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,286] Trial 9 finished with value: 0.1680971070540161 and parameters: {'alpha': 1.1917882156806343}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,290] Trial 10 finished with value: 0.10840377917554016 and parameters: {'alpha': 0.0006246259288267477}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,297] Trial 11 finished with value: 0.09110527143166787 and parameters: {'alpha': 1.1359718713540273e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,304] Trial 12 finished with value: 0.09111295705059876 and parameters: {'alpha': 1.1516408658315444e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,307] Trial 13 finished with value: 0.10486891811158137 and parameters: {'alpha': 0.00018242891173846762}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,310] Trial 14 finished with value: 0.12260243555212562 and parameters: {'alpha': 0.0029582099025094433}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,316] Trial 15 finished with value: 0.09315375482620365 and parameters: {'alpha': 4.378686066834927e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,319] Trial 16 finished with value: 0.1256417185595108 and parameters: {'alpha': 0.0033551250026302173}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,325] Trial 17 finished with value: 0.09652858728166658 and parameters: {'alpha': 8.584190492738238e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,332] Trial 18 finished with value: 0.09113079277120702 and parameters: {'alpha': 1.1875580397151664e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,334] Trial 19 finished with value: 0.11011011937333981 and parameters: {'alpha': 0.0007614012198963909}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,337] Trial 20 finished with value: 0.1680971070540161 and parameters: {'alpha': 8.546793362087987}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,347] Trial 21 finished with value: 0.09110092184703772 and parameters: {'alpha': 1.1270971378066817e-05}. Best is trial 4 with value: 0.09108769015369172.
[I 2026-03-14 19:58:45,356] Trial 22 finished with value: 0.09105686026669048 and parameters: {'alpha': 1.036372482803704e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,363] Trial 23 finished with value: 0.09412495077698459 and parameters: {'alpha': 5.697181829375646e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,367] Trial 24 finished with value: 0.10530940015525148 and parameters: {'alpha': 0.00023222998825310153}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,375] Trial 25 finished with value: 0.0924310871431387 and parameters: {'alpha': 3.3549194162946816e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,378] Trial 26 finished with value: 0.16766031384906097 and parameters: {'alpha': 0.019107928081777272}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,382] Trial 27 finished with value: 0.10924314799852768 and parameters: {'alpha': 0.0006933179332319932}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,386] Trial 28 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.06781460367088074}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,393] Trial 29 finished with value: 0.09827535968505087 and parameters: {'alpha': 0.00010448012297896099}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,400] Trial 30 finished with value: 0.09183634725818939 and parameters: {'alpha': 2.4519460176021556e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,410] Trial 31 finished with value: 0.0911243981830843 and parameters: {'alpha': 1.1749154641872503e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,418] Trial 32 finished with value: 0.09109459739867763 and parameters: {'alpha': 1.1141775431317892e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,424] Trial 33 finished with value: 0.09209466727560173 and parameters: {'alpha': 2.857245002918713e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,430] Trial 34 finished with value: 0.09758621848000543 and parameters: {'alpha': 9.732992832981287e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,437] Trial 35 finished with value: 0.09182660588356263 and parameters: {'alpha': 2.4362114285467945e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,440] Trial 36 finished with value: 0.10567593435382508 and parameters: {'alpha': 0.000307498253516021}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,447] Trial 37 finished with value: 0.09378317056611392 and parameters: {'alpha': 5.24791641577107e-05}. Best is trial 22 with value: 0.09105686026669048.

Optimizing Lasso for Device: 19.0

[I 2026-03-14 19:58:45,454] Trial 38 finished with value: 0.0915671363115249 and parameters: {'alpha': 2.0007561841507614e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,463] Trial 39 finished with value: 0.09613728666800274 and parameters: {'alpha': 8.139740328343758e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,466] Trial 40 finished with value: 0.11415349309980595 and parameters: {'alpha': 0.0015084872788427232}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,473] Trial 41 finished with value: 0.09107736797861218 and parameters: {'alpha': 1.0790074134472351e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,480] Trial 42 finished with value: 0.09151295074784785 and parameters: {'alpha': 1.9059793655518816e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,486] Trial 43 finished with value: 0.09114780835619851 and parameters: {'alpha': 1.2218480032577965e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,492] Trial 44 finished with value: 0.09280215820276536 and parameters: {'alpha': 3.872522055271584e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,501] Trial 45 finished with value: 0.09106981990703995 and parameters: {'alpha': 1.0633606297461302e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,509] Trial 46 finished with value: 0.10070075586755194 and parameters: {'alpha': 0.00012801336723787434}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,517] Trial 47 finished with value: 0.09154394595840475 and parameters: {'alpha': 1.960173621157461e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,524] Trial 48 finished with value: 0.09420277611589258 and parameters: {'alpha': 5.797728960482673e-05}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,527] Trial 49 finished with value: 0.10571230951336713 and parameters: {'alpha': 0.0003138917613305055}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,530] Trial 50 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.07578292151023422}. Best is trial 22 with value: 0.09105686026669048.
[I 2026-03-14 19:58:45,537] Trial 51 finished with value: 0.0910522845433462 and parameters: {'alpha': 1.0268251467125117e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,546] Trial 52 finished with value: 0.09149207276684013 and parameters: {'alpha': 1.8689892733614755e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,553] Trial 53 finished with value: 0.09293528415414701 and parameters: {'alpha': 4.061100557379916e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,561] Trial 54 finished with value: 0.09114195007889983 and parameters: {'alpha': 1.2100481009227599e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,567] Trial 55 finished with value: 0.09150301589868462 and parameters: {'alpha': 1.8883993119032142e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,570] Trial 56 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.37091746925360825}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,578] Trial 57 finished with value: 0.09442336099271097 and parameters: {'alpha': 6.078332383681053e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,583] Trial 58 finished with value: 0.10350856797263344 and parameters: {'alpha': 0.00015890314404147217}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,594] Trial 59 finished with value: 0.09108994934820647 and parameters: {'alpha': 1.1046504177985247e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,603] Trial 60 finished with value: 0.09250229276072769 and parameters: {'alpha': 3.456833732949465e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,612] Trial 61 finished with value: 0.09108992811299249 and parameters: {'alpha': 1.1046068502824155e-05}. Best is trial 51 with value: 0.0910522845433462.
[I 2026-03-14 19:58:45,620] Trial 62 finished with value: 0.09104363629907006 and parameters: {'alpha': 1.0090218139673622e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,627] Trial 63 finished with value: 0.0914377129703948 and parameters: {'alpha': 1.7718374613312866e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,634] Trial 64 finished with value: 0.09204312262781636 and parameters: {'alpha': 2.778003728370461e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,636] Trial 65 finished with value: 0.16725839143889853 and parameters: {'alpha': 0.0073248206937979255}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,643] Trial 66 finished with value: 0.09292121655885592 and parameters: {'alpha': 4.0403463240389576e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,649] Trial 67 finished with value: 0.09133342555474266 and parameters: {'alpha': 1.5809495486407316e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,655] Trial 68 finished with value: 0.09522243189602238 and parameters: {'alpha': 7.061283047213619e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,661] Trial 69 finished with value: 0.09213755438029768 and parameters: {'alpha': 2.9225981197447133e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,668] Trial 70 finished with value: 0.09104957168278918 and parameters: {'alpha': 1.0214419498163946e-05}. Best is trial 62 with value: 0.09104363629907006.
[I 2026-03-14 19:58:45,674] Trial 71 finished with value: 0.09104013505692571 and parameters: {'alpha': 1.0016930091844519e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,681] Trial 72 finished with value: 0.09133389283725295 and parameters: {'alpha': 1.5818215951146647e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,687] Trial 73 finished with value: 0.09207816096667595 and parameters: {'alpha': 2.8319968328522785e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,693] Trial 74 finished with value: 0.09105276778478844 and parameters: {'alpha': 1.0278345242931564e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,695] Trial 75 finished with value: 0.1680971070540161 and parameters: {'alpha': 5.364732709140487}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,702] Trial 76 finished with value: 0.09131333740673565 and parameters: {'alpha': 1.543242479159327e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,708] Trial 77 finished with value: 0.09105547807333415 and parameters: {'alpha': 1.0334904594094556e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,714] Trial 78 finished with value: 0.0932906383282652 and parameters: {'alpha': 4.572740574448469e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,720] Trial 79 finished with value: 0.09181559973993145 and parameters: {'alpha': 2.418718931786599e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,726] Trial 80 finished with value: 0.09105834819267505 and parameters: {'alpha': 1.0394745069009694e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,732] Trial 81 finished with value: 0.09137079928667483 and parameters: {'alpha': 1.650066548997047e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,738] Trial 82 finished with value: 0.09105247680492298 and parameters: {'alpha': 1.0272267358731462e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,744] Trial 83 finished with value: 0.09181623814916424 and parameters: {'alpha': 2.4197538582003803e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,750] Trial 84 finished with value: 0.09128258552642378 and parameters: {'alpha': 1.485082642335338e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,757] Trial 85 finished with value: 0.09105362075673819 and parameters: {'alpha': 1.0296162140725177e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,763] Trial 86 finished with value: 0.09250096343829174 and parameters: {'alpha': 3.454939293965688e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,768] Trial 87 finished with value: 0.09354544706571351 and parameters: {'alpha': 4.9260814036035884e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,775] Trial 88 finished with value: 0.09171817431784585 and parameters: {'alpha': 2.2586045572900068e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,780] Trial 89 finished with value: 0.09581946099885857 and parameters: {'alpha': 7.77150998139027e-05}. Best is trial 71 with value: 0.09104013505692571.
[I 2026-03-14 19:58:45,787] Trial 90 finished with value: 0.0910395261049067 and parameters: {'alpha': 1.0004178638904572e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,793] Trial 91 finished with value: 0.09120734536532192 and parameters: {'alpha': 1.3399199524796604e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,799] Trial 92 finished with value: 0.09130369072418416 and parameters: {'alpha': 1.5250334973078494e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,806] Trial 93 finished with value: 0.09166661344310173 and parameters: {'alpha': 2.172214546942454e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,812] Trial 94 finished with value: 0.09104746603381635 and parameters: {'alpha': 1.0170363542769596e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,818] Trial 95 finished with value: 0.09105184196955853 and parameters: {'alpha': 1.0259005676340035e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,825] Trial 96 finished with value: 0.0910401727210225 and parameters: {'alpha': 1.0017718584439488e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,831] Trial 97 finished with value: 0.0922884430392603 and parameters: {'alpha': 3.147560006033962e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,837] Trial 98 finished with value: 0.09128137178621187 and parameters: {'alpha': 1.4827735223446862e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,843] Trial 99 finished with value: 0.09169330003359212 and parameters: {'alpha': 2.2169524617095534e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,845] Trial 100 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.028374877167678968}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,851] Trial 101 finished with value: 0.09124551997853611 and parameters: {'alpha': 1.41432169907358e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,858] Trial 102 finished with value: 0.09104122742999705 and parameters: {'alpha': 1.0039798769204554e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,864] Trial 103 finished with value: 0.09136344439579204 and parameters: {'alpha': 1.636448789329123e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,870] Trial 104 finished with value: 0.09156603456617753 and parameters: {'alpha': 1.9988339920004097e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,876] Trial 105 finished with value: 0.09229838566469259 and parameters: {'alpha': 3.16218725938819e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,883] Trial 106 finished with value: 0.09105154389677754 and parameters: {'alpha': 1.025277757300026e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,889] Trial 107 finished with value: 0.09122213920587684 and parameters: {'alpha': 1.3688628241188737e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,895] Trial 108 finished with value: 0.0930140402591504 and parameters: {'alpha': 4.176597513560703e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,901] Trial 109 finished with value: 0.09183408711280573 and parameters: {'alpha': 2.4482993504392118e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,903] Trial 110 finished with value: 0.1116123643944592 and parameters: {'alpha': 0.0010572310453260368}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,910] Trial 111 finished with value: 0.09120493750484111 and parameters: {'alpha': 1.335194277637653e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,916] Trial 112 finished with value: 0.0910589955195576 and parameters: {'alpha': 1.0408239515078584e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,922] Trial 113 finished with value: 0.09151639355580839 and parameters: {'alpha': 1.912054916702408e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,929] Trial 114 finished with value: 0.09104312527969485 and parameters: {'alpha': 1.0079522796197985e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,934] Trial 115 finished with value: 0.09146872239707966 and parameters: {'alpha': 1.8274370646215107e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,941] Trial 116 finished with value: 0.09104165746039443 and parameters: {'alpha': 1.004880139538637e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,947] Trial 117 finished with value: 0.09197108199742773 and parameters: {'alpha': 2.666346834545574e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,949] Trial 118 finished with value: 0.12326779528873329 and parameters: {'alpha': 0.0030485768216808565}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,955] Trial 119 finished with value: 0.09125110905809031 and parameters: {'alpha': 1.4251206584399736e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,961] Trial 120 finished with value: 0.09380838671755587 and parameters: {'alpha': 5.281170750150032e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,967] Trial 121 finished with value: 0.09125187993007096 and parameters: {'alpha': 1.4266056972685293e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,970] Trial 122 finished with value: 0.1680971070540161 and parameters: {'alpha': 0.3184031625767667}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,976] Trial 123 finished with value: 0.09104233688940291 and parameters: {'alpha': 1.0063021875846046e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,982] Trial 124 finished with value: 0.09149031740778797 and parameters: {'alpha': 1.865871597099572e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,989] Trial 125 finished with value: 0.09104142104766953 and parameters: {'alpha': 1.0043852128078574e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:45,995] Trial 126 finished with value: 0.09104013845185968 and parameters: {'alpha': 1.0017001164312842e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,001] Trial 127 finished with value: 0.09248184637257678 and parameters: {'alpha': 3.427687408053035e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,008] Trial 128 finished with value: 0.09167478748821915 and parameters: {'alpha': 2.1857348114507358e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,014] Trial 129 finished with value: 0.09124848607138128 and parameters: {'alpha': 1.4200590896449065e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,020] Trial 130 finished with value: 0.09198894965858491 and parameters: {'alpha': 2.693921558417999e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,027] Trial 131 finished with value: 0.09104747915668363 and parameters: {'alpha': 1.0170638139011123e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,033] Trial 132 finished with value: 0.09119240451437051 and parameters: {'alpha': 1.3104886785882651e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,039] Trial 133 finished with value: 0.09142206617527926 and parameters: {'alpha': 1.743792480163561e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,045] Trial 134 finished with value: 0.09105532567628694 and parameters: {'alpha': 1.033172690940486e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,047] Trial 135 finished with value: 0.1494595231735512 and parameters: {'alpha': 0.0057011617449012845}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,054] Trial 136 finished with value: 0.09123680017196238 and parameters: {'alpha': 1.3974120682262993e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,060] Trial 137 finished with value: 0.09104345292551196 and parameters: {'alpha': 1.0086380386387858e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,066] Trial 138 finished with value: 0.0915481172771512 and parameters: {'alpha': 1.96748849308411e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,072] Trial 139 finished with value: 0.09122599764338955 and parameters: {'alpha': 1.3763906266537194e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,078] Trial 140 finished with value: 0.09185375058402079 and parameters: {'alpha': 2.4799914152194312e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,085] Trial 141 finished with value: 0.09104608346337537 and parameters: {'alpha': 1.0141430941566023e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,091] Trial 142 finished with value: 0.09104480851007696 and parameters: {'alpha': 1.0114749335164458e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,097] Trial 143 finished with value: 0.09146188314302851 and parameters: {'alpha': 1.8152166734479635e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,104] Trial 144 finished with value: 0.09128929270471062 and parameters: {'alpha': 1.4978132252418768e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,111] Trial 145 finished with value: 0.09124451842404355 and parameters: {'alpha': 1.412383800231406e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,118] Trial 146 finished with value: 0.0910551329923679 and parameters: {'alpha': 1.0327709188913549e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,124] Trial 147 finished with value: 0.09158307620053052 and parameters: {'alpha': 2.0285163190425687e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,131] Trial 148 finished with value: 0.09104041046414685 and parameters: {'alpha': 1.0022695703472871e-05}. Best is trial 90 with value: 0.0910395261049067.
[I 2026-03-14 19:58:46,137] Trial 149 finished with value: 0.0923786484961018 and parameters: {'alpha': 3.2791470829223745e-05}. Best is trial 90 with value: 0.0910395261049067.

Optimizing Lasso for Device: 11.0

[I 2026-03-14 19:58:47,286] Trial 37 finished with value: 0.02040979424810576 and parameters: {'alpha': 3.491843780485929e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,290] Trial 38 finished with value: 0.05831282177726149 and parameters: {'alpha': 0.2859567503399078}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,295] Trial 39 finished with value: 0.02050910434820649 and parameters: {'alpha': 0.00010762923332191633}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,299] Trial 40 finished with value: 0.020437100854737714 and parameters: {'alpha': 2.5071033789422114e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,309] Trial 41 finished with value: 0.019872557363246404 and parameters: {'alpha': 1.1342462571882354e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,318] Trial 42 finished with value: 0.01982676777935515 and parameters: {'alpha': 1.0296900093629114e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,323] Trial 43 finished with value: 0.02043718738144089 and parameters: {'alpha': 2.503724338387429e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,328] Trial 44 finished with value: 0.020388474064908818 and parameters: {'alpha': 6.993272256807347e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,332] Trial 45 finished with value: 0.02043355428049073 and parameters: {'alpha': 2.654634343563324e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,336] Trial 46 finished with value: 0.05831282177726149 and parameters: {'alpha': 2.0355081481385384}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,340] Trial 47 finished with value: 0.02039112603669355 and parameters: {'alpha': 4.44472323144574e-05}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,345] Trial 48 finished with value: 0.022249567132057748 and parameters: {'alpha': 0.0002494872282865249}. Best is trial 31 with value: 0.019822453551504044.
[I 2026-03-14 19:58:47,355] Trial 49 finished with value: 0.019816672685024222 and parameters: {'alpha': 1.0044947312783288e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,358] Trial 50 finished with value: 0.05831282177726149 and parameters: {'alpha': 0.1782776295699419}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,367] Trial 51 finished with value: 0.01983129266459367 and parameters: {'alpha': 1.0406768353743907e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,374] Trial 52 finished with value: 0.020452243784767288 and parameters: {'alpha': 1.9842102500170146e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,379] Trial 53 finished with value: 0.020441875888166216 and parameters: {'alpha': 2.337402604078927e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,388] Trial 54 finished with value: 0.01982223802487086 and parameters: {'alpha': 1.0184542250117371e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,395] Trial 55 finished with value: 0.02045187802918141 and parameters: {'alpha': 1.9989394095244825e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,399] Trial 56 finished with value: 0.02041396179957936 and parameters: {'alpha': 8.324338734712199e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,404] Trial 57 finished with value: 0.020394702478044514 and parameters: {'alpha': 4.213150082253596e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,411] Trial 58 finished with value: 0.02039082896772128 and parameters: {'alpha': 1.8920729318818142e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,415] Trial 59 finished with value: 0.020598365965410752 and parameters: {'alpha': 0.0001226499120539429}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,420] Trial 60 finished with value: 0.02040881506705339 and parameters: {'alpha': 3.5318035350487114e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,430] Trial 61 finished with value: 0.01982743690855608 and parameters: {'alpha': 1.0313371629974423e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,440] Trial 62 finished with value: 0.019823206367486766 and parameters: {'alpha': 1.0208717328069675e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,446] Trial 63 finished with value: 0.020291082562431666 and parameters: {'alpha': 1.7772866092544097e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,451] Trial 64 finished with value: 0.020238892161190777 and parameters: {'alpha': 1.7107678619324926e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,461] Trial 65 finished with value: 0.01981673447089845 and parameters: {'alpha': 1.0046520885098365e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,464] Trial 66 finished with value: 0.057944022857928774 and parameters: {'alpha': 0.003159983688566716}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,469] Trial 67 finished with value: 0.02038156215969113 and parameters: {'alpha': 5.6715163494156305e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,474] Trial 68 finished with value: 0.020421334229067823 and parameters: {'alpha': 3.062075140622801e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,478] Trial 69 finished with value: 0.05823728106511632 and parameters: {'alpha': 0.013252690878074793}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,484] Trial 70 finished with value: 0.020208146354760738 and parameters: {'alpha': 1.670070711470838e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,494] Trial 71 finished with value: 0.019817579547034014 and parameters: {'alpha': 1.0068008506828714e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,502] Trial 72 finished with value: 0.020051757832826887 and parameters: {'alpha': 1.4523670288814277e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,511] Trial 73 finished with value: 0.019835505190391862 and parameters: {'alpha': 1.0508667750821954e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,515] Trial 74 finished with value: 0.020421750251888436 and parameters: {'alpha': 3.0476252690093826e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,519] Trial 75 finished with value: 0.05831282177726149 and parameters: {'alpha': 8.459214182663073}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,524] Trial 76 finished with value: 0.020381850686466453 and parameters: {'alpha': 5.544133142825067e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,532] Trial 77 finished with value: 0.02006769688238938 and parameters: {'alpha': 1.4764061458865425e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,536] Trial 78 finished with value: 0.020440067444682002 and parameters: {'alpha': 9.174704852097824e-05}. Best is trial 49 with value: 0.019816672685024222.
[I 2026-03-14 19:58:47,546] Trial 79 finished with value: 0.01981620846531905 and parameters: {'alpha': 1.0033109528229953e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,551] Trial 80 finished with value: 0.020435255245514445 and parameters: {'alpha': 2.5817035220400178e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,561] Trial 81 finished with value: 0.019820513030980993 and parameters: {'alpha': 1.014118248243185e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,568] Trial 82 finished with value: 0.020101130728608963 and parameters: {'alpha': 1.5254057648708713e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,573] Trial 83 finished with value: 0.020395104926794583 and parameters: {'alpha': 4.189411784889021e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,578] Trial 84 finished with value: 0.020439008956634187 and parameters: {'alpha': 2.4428849362789757e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,586] Trial 85 finished with value: 0.02006104439849649 and parameters: {'alpha': 1.4664112013700369e-05}. Best is trial 79 with value: 0.01981620846531905.
[I 2026-03-14 19:58:47,595] Trial 86 finished with value: 0.019816148417776885 and parameters: {'alpha': 1.0031577693084773e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,600] Trial 87 finished with value: 0.02044879831723149 and parameters: {'alpha': 2.098521488142917e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,605] Trial 88 finished with value: 0.020381523332190683 and parameters: {'alpha': 5.946827168277527e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,609] Trial 89 finished with value: 0.020418678086295276 and parameters: {'alpha': 3.155626963249445e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,617] Trial 90 finished with value: 0.020146261111653224 and parameters: {'alpha': 1.5885406889272622e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,627] Trial 91 finished with value: 0.019935379613337318 and parameters: {'alpha': 1.2581253955948624e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,633] Trial 92 finished with value: 0.020451164061416328 and parameters: {'alpha': 2.0254366983576157e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,644] Trial 93 finished with value: 0.019821530536366268 and parameters: {'alpha': 1.0166774248931638e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,654] Trial 94 finished with value: 0.01982750948784003 and parameters: {'alpha': 1.0315156638111556e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,658] Trial 95 finished with value: 0.020404821397357033 and parameters: {'alpha': 3.7019664847414473e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,667] Trial 96 finished with value: 0.019989600375904384 and parameters: {'alpha': 1.353175897578354e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,672] Trial 97 finished with value: 0.020442557250252527 and parameters: {'alpha': 2.3172902510032255e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,676] Trial 98 finished with value: 0.02038678886485202 and parameters: {'alpha': 4.7952164492002434e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,681] Trial 99 finished with value: 0.03589555421416266 and parameters: {'alpha': 0.0007660630011287128}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,688] Trial 100 finished with value: 0.020390664423278738 and parameters: {'alpha': 1.8918873808090613e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,697] Trial 101 finished with value: 0.019851189936646002 and parameters: {'alpha': 1.0873790091451811e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,707] Trial 102 finished with value: 0.019828241582992213 and parameters: {'alpha': 1.0332182680571234e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,714] Trial 103 finished with value: 0.020105053751978793 and parameters: {'alpha': 1.5310784493679657e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,719] Trial 104 finished with value: 0.02042832827658308 and parameters: {'alpha': 2.8278143012316906e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,728] Trial 105 finished with value: 0.01996738732953631 and parameters: {'alpha': 1.3153742839748256e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,733] Trial 106 finished with value: 0.020449328120282745 and parameters: {'alpha': 2.079686019793771e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,738] Trial 107 finished with value: 0.020417186352054785 and parameters: {'alpha': 3.2093039190901385e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,748] Trial 108 finished with value: 0.019818421763977512 and parameters: {'alpha': 1.008936632104635e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,753] Trial 109 finished with value: 0.020246670320325236 and parameters: {'alpha': 1.7213034583024113e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,758] Trial 110 finished with value: 0.02038916319498337 and parameters: {'alpha': 7.04939869272632e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,768] Trial 111 finished with value: 0.019819671636966706 and parameters: {'alpha': 1.0119992585039061e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,778] Trial 112 finished with value: 0.019816763543317604 and parameters: {'alpha': 1.0047261141234022e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,786] Trial 113 finished with value: 0.02001901063446597 and parameters: {'alpha': 1.4012502336678816e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,791] Trial 114 finished with value: 0.02043777773440639 and parameters: {'alpha': 2.4809939962260868e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,800] Trial 115 finished with value: 0.01998511719525894 and parameters: {'alpha': 1.3456955424419765e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,804] Trial 116 finished with value: 0.05831282177726149 and parameters: {'alpha': 3.1787756467600605}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,811] Trial 117 finished with value: 0.020377123707972504 and parameters: {'alpha': 1.8768510328746547e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,821] Trial 118 finished with value: 0.01982139502267595 and parameters: {'alpha': 1.0163368869454823e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,825] Trial 119 finished with value: 0.02040254276328652 and parameters: {'alpha': 3.805191623446776e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,829] Trial 120 finished with value: 0.05831282177726149 and parameters: {'alpha': 0.08961864130738512}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,839] Trial 121 finished with value: 0.019824317988252023 and parameters: {'alpha': 1.0236355279346656e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,845] Trial 122 finished with value: 0.020299875181736357 and parameters: {'alpha': 1.7877186522341275e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,854] Trial 123 finished with value: 0.019958424301967124 and parameters: {'alpha': 1.2996934784789941e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,859] Trial 124 finished with value: 0.02043612605869057 and parameters: {'alpha': 2.54569104692178e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,869] Trial 125 finished with value: 0.01981873971443101 and parameters: {'alpha': 1.0097419825139156e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,877] Trial 126 finished with value: 0.020016375029926578 and parameters: {'alpha': 1.3970072254141448e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,884] Trial 127 finished with value: 0.02030992341289814 and parameters: {'alpha': 1.799704728136904e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,894] Trial 128 finished with value: 0.019817173492182382 and parameters: {'alpha': 1.0057687828794894e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,899] Trial 129 finished with value: 0.020444435454353708 and parameters: {'alpha': 2.2493198045730856e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,903] Trial 130 finished with value: 0.05831282177726149 and parameters: {'alpha': 0.5723149290603292}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,913] Trial 131 finished with value: 0.019819547422839895 and parameters: {'alpha': 1.0116862800187396e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,921] Trial 132 finished with value: 0.019984169389404005 and parameters: {'alpha': 1.3440865320218132e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,930] Trial 133 finished with value: 0.01996064973151743 and parameters: {'alpha': 1.3036352728534049e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,936] Trial 134 finished with value: 0.02028475036631011 and parameters: {'alpha': 1.7696610799734624e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,946] Trial 135 finished with value: 0.019833291804965555 and parameters: {'alpha': 1.045531368422389e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,950] Trial 136 finished with value: 0.020425155962501097 and parameters: {'alpha': 2.931749147318256e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,958] Trial 137 finished with value: 0.020139175880787674 and parameters: {'alpha': 1.578800823143986e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,968] Trial 138 finished with value: 0.019821854215231142 and parameters: {'alpha': 1.01749064767988e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,975] Trial 139 finished with value: 0.02044783492960149 and parameters: {'alpha': 1.9644747623600405e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,983] Trial 140 finished with value: 0.019978881595631305 and parameters: {'alpha': 1.3351655234444332e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,993] Trial 141 finished with value: 0.01982490740224018 and parameters: {'alpha': 1.0250969749603395e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:47,998] Trial 142 finished with value: 0.02044143993458205 and parameters: {'alpha': 2.3510693822534423e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:48,008] Trial 143 finished with value: 0.01983219625981427 and parameters: {'alpha': 1.042875562860928e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:48,018] Trial 144 finished with value: 0.019816166000268053 and parameters: {'alpha': 1.003202622897716e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:48,025] Trial 145 finished with value: 0.020138728309790348 and parameters: {'alpha': 1.578176260212052e-05}. Best is trial 86 with value: 0.019816148417776885.
[I 2026-03-14 19:58:48,033] Trial 146 finished with value: 0.019991473590582835 and parameters: {'alpha': 1.356323539214943e-05}. Best is trial 86 with value: 0.019816148417776885.

Optimizing Lasso for Device: 7.0

[I 2026-03-14 19:58:49,510] Trial 108 finished with value: 0.00918423746960147 and parameters: {'alpha': 1.3231912121615289e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,512] Trial 109 finished with value: 0.009221664925612565 and parameters: {'alpha': 1.7822245458903613e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,514] Trial 110 finished with value: 0.009329692133679866 and parameters: {'alpha': 2.5985478728749516e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,516] Trial 111 finished with value: 0.009167650743836646 and parameters: {'alpha': 1.0021436350225627e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,518] Trial 112 finished with value: 0.009194290723671271 and parameters: {'alpha': 1.4669324452388389e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,521] Trial 113 finished with value: 0.009222146717083702 and parameters: {'alpha': 1.7870740010179917e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,523] Trial 114 finished with value: 0.009168082530905905 and parameters: {'alpha': 1.0134529516672365e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,525] Trial 115 finished with value: 0.00983567660386912 and parameters: {'alpha': 4.6446939282757966e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,527] Trial 116 finished with value: 0.009181091397213936 and parameters: {'alpha': 1.2741258193387533e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,529] Trial 117 finished with value: 0.009314352745535388 and parameters: {'alpha': 2.5017486914359717e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,531] Trial 118 finished with value: 0.009550278325174879 and parameters: {'alpha': 3.668726420688687e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,534] Trial 119 finished with value: 0.009167811696600314 and parameters: {'alpha': 1.0063963525944708e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,536] Trial 120 finished with value: 0.009232903912606328 and parameters: {'alpha': 1.890503682582187e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,538] Trial 121 finished with value: 0.009168414390812528 and parameters: {'alpha': 1.0220018060037934e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,541] Trial 122 finished with value: 0.009197801701255798 and parameters: {'alpha': 1.51265459545832e-05}. Best is trial 32 with value: 0.0091676302021273.
[I 2026-03-14 19:58:49,543] Trial 123 finished with value: 0.009167587915354186 and parameters: {'alpha': 1.0004818665965825e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,546] Trial 124 finished with value: 0.009190976317213006 and parameters: {'alpha': 1.4217865301986674e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,548] Trial 125 finished with value: 0.009280696278913089 and parameters: {'alpha': 2.2741559317734063e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,550] Trial 126 finished with value: 0.009167763704608409 and parameters: {'alpha': 1.0051313898664273e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,553] Trial 127 finished with value: 0.009219459089080787 and parameters: {'alpha': 1.7597026410933784e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,555] Trial 128 finished with value: 0.03380969758487817 and parameters: {'alpha': 3.052244626567167}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,557] Trial 129 finished with value: 0.009402322940321941 and parameters: {'alpha': 3.006091072554848e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,559] Trial 130 finished with value: 0.009185080959426339 and parameters: {'alpha': 1.3359501537140774e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,561] Trial 131 finished with value: 0.009178077673828864 and parameters: {'alpha': 1.2234095305505944e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,564] Trial 132 finished with value: 0.009168911177673975 and parameters: {'alpha': 1.0347390219721547e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,566] Trial 133 finished with value: 0.009234790919158508 and parameters: {'alpha': 1.9077256240700937e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,569] Trial 134 finished with value: 0.009168492293724184 and parameters: {'alpha': 1.0240086393686017e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,571] Trial 135 finished with value: 0.03380969758487817 and parameters: {'alpha': 0.02801883199532434}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,573] Trial 136 finished with value: 0.009190265175154918 and parameters: {'alpha': 1.411848070041673e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,575] Trial 137 finished with value: 0.009304178197818595 and parameters: {'alpha': 2.4354713514113415e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,578] Trial 138 finished with value: 0.009208731964737989 and parameters: {'alpha': 1.64461221014495e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,580] Trial 139 finished with value: 0.009258793171094942 and parameters: {'alpha': 2.1103741576682106e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,583] Trial 140 finished with value: 0.009182399834199446 and parameters: {'alpha': 1.2950778737318538e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,585] Trial 141 finished with value: 0.009179617421653788 and parameters: {'alpha': 1.2496121941834379e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,587] Trial 142 finished with value: 0.00917171324971323 and parameters: {'alpha': 1.0998586927281803e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,589] Trial 143 finished with value: 0.009226371793131375 and parameters: {'alpha': 1.8287817665636164e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,591] Trial 144 finished with value: 0.009167947575190486 and parameters: {'alpha': 1.0099649114306957e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,593] Trial 145 finished with value: 0.009356765592153158 and parameters: {'alpha': 2.758887234707434e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,596] Trial 146 finished with value: 0.009168008616057096 and parameters: {'alpha': 1.0115491138575505e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,598] Trial 147 finished with value: 0.00919907967123437 and parameters: {'alpha': 1.5289227788839137e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,600] Trial 148 finished with value: 0.00921659049216436 and parameters: {'alpha': 1.7299557437428802e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,603] Trial 149 finished with value: 0.009168380257310526 and parameters: {'alpha': 1.021122503173822e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,605] Trial 150 finished with value: 0.009466315986108878 and parameters: {'alpha': 3.3133951237536754e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,607] Trial 151 finished with value: 0.009181082717366016 and parameters: {'alpha': 1.2739825910011342e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,611] Trial 152 finished with value: 0.009250899505771527 and parameters: {'alpha': 2.0467751468149194e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,614] Trial 153 finished with value: 0.009168491335651743 and parameters: {'alpha': 1.0239839587540418e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,616] Trial 154 finished with value: 0.009190723703219049 and parameters: {'alpha': 1.4182652607752648e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,619] Trial 155 finished with value: 0.009293666440321547 and parameters: {'alpha': 2.3650004960609725e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,621] Trial 156 finished with value: 0.009206704031480762 and parameters: {'alpha': 1.621421024271852e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,623] Trial 157 finished with value: 0.009167701959527808 and parameters: {'alpha': 1.0034982639522822e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,625] Trial 158 finished with value: 0.009183454053508176 and parameters: {'alpha': 1.3112774691388115e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,628] Trial 159 finished with value: 0.009168382740244417 and parameters: {'alpha': 1.0211864652834626e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,630] Trial 160 finished with value: 0.009167795909626282 and parameters: {'alpha': 1.005981382284225e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,633] Trial 161 finished with value: 0.00916822603738676 and parameters: {'alpha': 1.0171496903229426e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,635] Trial 162 finished with value: 0.009192155768282514 and parameters: {'alpha': 1.4380679238296064e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,638] Trial 163 finished with value: 0.009234569833620383 and parameters: {'alpha': 1.9057154800825262e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,640] Trial 164 finished with value: 0.009167744640048655 and parameters: {'alpha': 1.004627141976994e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,643] Trial 165 finished with value: 0.009187858121093934 and parameters: {'alpha': 1.3773024766459439e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,646] Trial 166 finished with value: 0.009221049996159981 and parameters: {'alpha': 1.7759958441733728e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,648] Trial 167 finished with value: 0.0092972185774891 and parameters: {'alpha': 2.3890867465197418e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,650] Trial 168 finished with value: 0.009184014080723068 and parameters: {'alpha': 1.3198047704861096e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,653] Trial 169 finished with value: 0.009212129762947175 and parameters: {'alpha': 1.6822847114972975e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,655] Trial 170 finished with value: 0.009167986330328786 and parameters: {'alpha': 1.0109713160730263e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,657] Trial 171 finished with value: 0.009169058297710558 and parameters: {'alpha': 1.0384771712842628e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,659] Trial 172 finished with value: 0.009182971638461395 and parameters: {'alpha': 1.3038970829831732e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,662] Trial 173 finished with value: 0.009168166997326274 and parameters: {'alpha': 1.0156287771668022e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,664] Trial 174 finished with value: 0.00920573963194416 and parameters: {'alpha': 1.61017707833627e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,666] Trial 175 finished with value: 0.00925378196854432 and parameters: {'alpha': 2.0704399609307298e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,668] Trial 176 finished with value: 0.00918186099367296 and parameters: {'alpha': 1.2865989337569353e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,670] Trial 177 finished with value: 0.009168685645619968 and parameters: {'alpha': 1.0289883066630893e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,672] Trial 178 finished with value: 0.009341438382630924 and parameters: {'alpha': 2.6695956760300652e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,674] Trial 179 finished with value: 0.009167654085638495 and parameters: {'alpha': 1.0022320239784753e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,677] Trial 180 finished with value: 0.009210987262464861 and parameters: {'alpha': 1.6697200708142163e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,679] Trial 181 finished with value: 0.009168170366130622 and parameters: {'alpha': 1.0157155599174588e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,681] Trial 182 finished with value: 0.009187016280142428 and parameters: {'alpha': 1.364879379212063e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,683] Trial 183 finished with value: 0.009186377713087543 and parameters: {'alpha': 1.3553868397702084e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,686] Trial 184 finished with value: 0.009229410363650931 and parameters: {'alpha': 1.857868579604158e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,688] Trial 185 finished with value: 0.009183715660617087 and parameters: {'alpha': 1.3152653934030241e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,690] Trial 186 finished with value: 0.009273799916996698 and parameters: {'alpha': 2.2239179677241024e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,692] Trial 187 finished with value: 0.03380969758487817 and parameters: {'alpha': 0.8836596681462185}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,694] Trial 188 finished with value: 0.009168257893435207 and parameters: {'alpha': 1.0179703243601914e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,696] Trial 189 finished with value: 0.02405735981159466 and parameters: {'alpha': 0.0007178906862582169}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,698] Trial 190 finished with value: 0.009167817276998762 and parameters: {'alpha': 1.0065430367956092e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,701] Trial 191 finished with value: 0.009168426225628527 and parameters: {'alpha': 1.0223066791221934e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,703] Trial 192 finished with value: 0.009189491444230693 and parameters: {'alpha': 1.4009372270679102e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,705] Trial 193 finished with value: 0.009206359576262183 and parameters: {'alpha': 1.617421026635634e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,707] Trial 194 finished with value: 0.00916775693568673 and parameters: {'alpha': 1.0049523553377254e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,709] Trial 195 finished with value: 0.009186203185968066 and parameters: {'alpha': 1.3527878773364228e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,712] Trial 196 finished with value: 0.009226490898738648 and parameters: {'alpha': 1.8299306443764196e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,714] Trial 197 finished with value: 0.009182775913572637 and parameters: {'alpha': 1.3008905401487177e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,716] Trial 198 finished with value: 0.009167967117809765 and parameters: {'alpha': 1.0104723998212942e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,719] Trial 199 finished with value: 0.00921713054190338 and parameters: {'alpha': 1.735578802429366e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,721] Trial 200 finished with value: 0.009270706757558436 and parameters: {'alpha': 2.201066829907573e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,723] Trial 201 finished with value: 0.009167972560524193 and parameters: {'alpha': 1.0106137378040157e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,725] Trial 202 finished with value: 0.00916834886584496 and parameters: {'alpha': 1.0203138371159144e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,727] Trial 203 finished with value: 0.009184805567626577 and parameters: {'alpha': 1.3317890876141083e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,730] Trial 204 finished with value: 0.009168208762063184 and parameters: {'alpha': 1.0167046659329183e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,732] Trial 205 finished with value: 0.009182848214278772 and parameters: {'alpha': 1.3020011560307542e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,734] Trial 206 finished with value: 0.009203369373422187 and parameters: {'alpha': 1.5818264258160632e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,736] Trial 207 finished with value: 0.009183298044176419 and parameters: {'alpha': 1.3088939259442393e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,738] Trial 208 finished with value: 0.03380969758487817 and parameters: {'alpha': 0.1259538636904609}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,740] Trial 209 finished with value: 0.009167623206570042 and parameters: {'alpha': 1.0014152883550576e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,742] Trial 210 finished with value: 0.009230097179946392 and parameters: {'alpha': 1.8643433886706702e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,745] Trial 211 finished with value: 0.009168784188670944 and parameters: {'alpha': 1.0315084424486411e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,747] Trial 212 finished with value: 0.00916771941326084 and parameters: {'alpha': 1.0039599062958938e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,750] Trial 213 finished with value: 0.009184640036101607 and parameters: {'alpha': 1.3292879687803217e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,753] Trial 214 finished with value: 0.009182407604423879 and parameters: {'alpha': 1.2951981569896723e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,755] Trial 215 finished with value: 0.00920186817440264 and parameters: {'alpha': 1.5635726027111086e-05}. Best is trial 123 with value: 0.009167587915354186.
[I 2026-03-14 19:58:49,758] Trial 216 finished with value: 0.009167610088007355 and parameters: {'alpha': 1.0010683090578026e-05}. Best is trial 123 with value: 0.009167587915354186.

Best Lasso Alphas found: {np.float64(19.0): 1.0001370633335225e-05, np.float64(11.0): 1.0000293643965711e-05, np.float64(7.0): 1.0004767844784342e-05}

In [109]:
from sklearn.linear_model import Ridge

ridge_models = {}
ridge_best_alphas = {}

for d_type in daily_train['deviceType'].unique():
    df_type = daily_train[daily_train['deviceType'] == d_type].dropna(subset=feature_cols_present + [TARGET_COL])
    if len(df_type) < 20: continue

    X_t, y_t = df_type[feature_cols_present].values, df_type[TARGET_COL].values

    def objective(trial):
        alpha = trial.suggest_float("alpha", 1e-3, 100.0, log=True)
        model = Ridge(alpha=alpha, random_state=42)
        model.fit(X_t, y_t)
        preds = model.predict(X_t)
        return mean_absolute_error(y_t, preds)

    print(f"Optimizing Ridge for Device: {d_type}")
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=300, show_progress_bar=False)

    best_alpha = study.best_params['alpha']
    ridge_models[d_type] = Ridge(alpha=best_alpha).fit(X_t, y_t)
    ridge_best_alphas[d_type] = best_alpha

print("\nBest Ridge Alphas found:", ridge_best_alphas)

[I 2026-03-14 19:59:01,679] A new study created in memory with name: no-name-d9cb1818-832d-43bc-bb68-abef88038941
[I 2026-03-14 19:59:01,684] Trial 0 finished with value: 0.09095064107475483 and parameters: {'alpha': 0.04753733452001211}. Best is trial 0 with value: 0.09095064107475483.
[I 2026-03-14 19:59:01,687] Trial 1 finished with value: 0.09078349576770292 and parameters: {'alpha': 0.027898279451983587}. Best is trial 1 with value: 0.09078349576770292.
[I 2026-03-14 19:59:01,690] Trial 2 finished with value: 0.09072676054056673 and parameters: {'alpha': 0.02147177015648667}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,692] Trial 3 finished with value: 0.09952302671150454 and parameters: {'alpha': 3.1591397076051004}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,695] Trial 4 finished with value: 0.10054204287683427 and parameters: {'alpha': 4.444336467606881}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,698] Trial 5 finished with value: 0.09116613594468523 and parameters: {'alpha': 0.07430670524443143}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,700] Trial 6 finished with value: 0.09765500127253232 and parameters: {'alpha': 1.7436774296943363}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,704] Trial 7 finished with value: 0.11221553849710025 and parameters: {'alpha': 53.659427946308135}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,707] Trial 8 finished with value: 0.1102689550352807 and parameters: {'alpha': 41.415284311356984}. Best is trial 2 with value: 0.09072676054056673.
[I 2026-03-14 19:59:01,710] Trial 9 finished with value: 0.09057256128359087 and parameters: {'alpha': 0.001699585349421501}. Best is trial 9 with value: 0.09057256128359087.
[I 2026-03-14 19:59:01,713] Trial 10 finished with value: 0.09056927012705983 and parameters: {'alpha': 0.0011100716138401725}. Best is trial 10 with value: 0.09056927012705983.
[I 2026-03-14 19:59:01,716] Trial 11 finished with value: 0.09056886700268195 and parameters: {'alpha': 0.001034420158609175}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,719] Trial 12 finished with value: 0.09056912829831351 and parameters: {'alpha': 0.0010835306648426563}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,721] Trial 13 finished with value: 0.09059180377593502 and parameters: {'alpha': 0.004728758739026124}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,724] Trial 14 finished with value: 0.09060341804050971 and parameters: {'alpha': 0.006371729746839757}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,727] Trial 15 finished with value: 0.09271596407528804 and parameters: {'alpha': 0.30018670851257284}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,731] Trial 16 finished with value: 0.09057882145383836 and parameters: {'alpha': 0.0027492787761589418}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,735] Trial 17 finished with value: 0.09060465057416736 and parameters: {'alpha': 0.006542631617535203}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,738] Trial 18 finished with value: 0.09191066881836245 and parameters: {'alpha': 0.1765553849025409}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,742] Trial 19 finished with value: 0.09063816677838143 and parameters: {'alpha': 0.011007134774782223}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,744] Trial 20 finished with value: 0.09453818247390093 and parameters: {'alpha': 0.6514374110538532}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,748] Trial 21 finished with value: 0.09056934693420107 and parameters: {'alpha': 0.0011244092778900788}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,751] Trial 22 finished with value: 0.09056894929935135 and parameters: {'alpha': 0.001049889157757747}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,754] Trial 23 finished with value: 0.09057725901255614 and parameters: {'alpha': 0.0024921019279187375}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,756] Trial 24 finished with value: 0.09064346868371952 and parameters: {'alpha': 0.011671836866615092}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,760] Trial 25 finished with value: 0.09056888307325764 and parameters: {'alpha': 0.0010374409822359384}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,762] Trial 26 finished with value: 0.0905838679791874 and parameters: {'alpha': 0.0035510939219803588}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,766] Trial 27 finished with value: 0.09136662469573573 and parameters: {'alpha': 0.10061802296319503}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,769] Trial 28 finished with value: 0.09068609022044016 and parameters: {'alpha': 0.016773510417762445}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,771] Trial 29 finished with value: 0.0908370104380259 and parameters: {'alpha': 0.03406684818719889}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,774] Trial 30 finished with value: 0.10554440424789291 and parameters: {'alpha': 17.889931294501757}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,777] Trial 31 finished with value: 0.090570171536647 and parameters: {'alpha': 0.0012766040767704535}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,779] Trial 32 finished with value: 0.0905772664077961 and parameters: {'alpha': 0.0024933241414389715}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,782] Trial 33 finished with value: 0.09059325663073567 and parameters: {'alpha': 0.00493862866977392}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,784] Trial 34 finished with value: 0.09056925703286278 and parameters: {'alpha': 0.0011076272106245806}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,786] Trial 35 finished with value: 0.09062084260687774 and parameters: {'alpha': 0.008755923572642346}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,789] Trial 36 finished with value: 0.09057636337232158 and parameters: {'alpha': 0.0023434104593259603}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,791] Trial 37 finished with value: 0.09077084768380993 and parameters: {'alpha': 0.02646066229280548}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,794] Trial 38 finished with value: 0.09058285441531448 and parameters: {'alpha': 0.003392402023580328}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,796] Trial 39 finished with value: 0.0911588269099944 and parameters: {'alpha': 0.07337394372289277}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,799] Trial 40 finished with value: 0.09057301307285143 and parameters: {'alpha': 0.0017772051769231073}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,801] Trial 41 finished with value: 0.09056893362926036 and parameters: {'alpha': 0.001046943804314606}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,804] Trial 42 finished with value: 0.09056886937777925 and parameters: {'alpha': 0.0010348666141703732}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,806] Trial 43 finished with value: 0.09057442785496057 and parameters: {'alpha': 0.002018036311346692}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,809] Trial 44 finished with value: 0.09058865185918008 and parameters: {'alpha': 0.004271062213062857}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,811] Trial 45 finished with value: 0.09057372322316352 and parameters: {'alpha': 0.0018982236855002352}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,814] Trial 46 finished with value: 0.10223411707337546 and parameters: {'alpha': 7.691006601155983}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,816] Trial 47 finished with value: 0.09056897823306585 and parameters: {'alpha': 0.0010553274268227824}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,818] Trial 48 finished with value: 0.09061806889853263 and parameters: {'alpha': 0.008381808102699671}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,821] Trial 49 finished with value: 0.09066968811315798 and parameters: {'alpha': 0.014842880708971993}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,823] Trial 50 finished with value: 0.09461260440277025 and parameters: {'alpha': 0.6687611986240621}. Best is trial 11 with value: 0.09056886700268195.
[I 2026-03-14 19:59:01,826] Trial 51 finished with value: 0.09056876709672468 and parameters: {'alpha': 0.0010156395422962687}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,828] Trial 52 finished with value: 0.09057225327281221 and parameters: {'alpha': 0.0016465831525065441}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,831] Trial 53 finished with value: 0.09059596832059098 and parameters: {'alpha': 0.005327328957932601}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,833] Trial 54 finished with value: 0.0905822587905327 and parameters: {'alpha': 0.00329888049337202}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,836] Trial 55 finished with value: 0.09057214677216685 and parameters: {'alpha': 0.0016282572643183117}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,838] Trial 56 finished with value: 0.09057146289822361 and parameters: {'alpha': 0.0015079921754607472}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,841] Trial 57 finished with value: 0.09058154790294312 and parameters: {'alpha': 0.003187113496777761}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,843] Trial 58 finished with value: 0.09056923326682949 and parameters: {'alpha': 0.0011031905344924932}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,846] Trial 59 finished with value: 0.09060303425623423 and parameters: {'alpha': 0.006318575768090068}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,849] Trial 60 finished with value: 0.09057486774000784 and parameters: {'alpha': 0.0020925303610224723}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,852] Trial 61 finished with value: 0.09056901433721859 and parameters: {'alpha': 0.0010621132097056922}. Best is trial 51 with value: 0.09056876709672468.
[I 2026-03-14 19:59:01,856] Trial 62 finished with value: 0.09056875011568877 and parameters: {'alpha': 0.0010124472152455003}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,859] Trial 63 finished with value: 0.09057735462322032 and parameters: {'alpha': 0.002507903956532263}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,862] Trial 64 finished with value: 0.09057170736051952 and parameters: {'alpha': 0.0015514054774720856}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,865] Trial 65 finished with value: 0.09058507092133042 and parameters: {'alpha': 0.0037369987896040714}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,867] Trial 66 finished with value: 0.0905688760890817 and parameters: {'alpha': 0.0010361281561888699}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,870] Trial 67 finished with value: 0.11780987853451436 and parameters: {'alpha': 95.80763213095382}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,873] Trial 68 finished with value: 0.09057132255023163 and parameters: {'alpha': 0.0014830251484214134}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,875] Trial 69 finished with value: 0.09057989222900342 and parameters: {'alpha': 0.002923327132907389}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,878] Trial 70 finished with value: 0.09061320241973635 and parameters: {'alpha': 0.007721104830281729}. Best is trial 62 with value: 0.09056875011568877.

Optimizing Ridge for Device: 19.0

[I 2026-03-14 19:59:01,880] Trial 71 finished with value: 0.09056882440507696 and parameters: {'alpha': 0.0010264127587983295}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,883] Trial 72 finished with value: 0.09057131156929826 and parameters: {'alpha': 0.0014810716812187926}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,887] Trial 73 finished with value: 0.09056891387630864 and parameters: {'alpha': 0.0010432309716895}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,890] Trial 74 finished with value: 0.09057579102556475 and parameters: {'alpha': 0.0022479167185133035}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,893] Trial 75 finished with value: 0.09056875225143907 and parameters: {'alpha': 0.0010128487256609363}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,896] Trial 76 finished with value: 0.09059526330857548 and parameters: {'alpha': 0.005226892278643366}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,898] Trial 77 finished with value: 0.09057459595129974 and parameters: {'alpha': 0.002046523234887281}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,901] Trial 78 finished with value: 0.09058735051876776 and parameters: {'alpha': 0.0040794884125881226}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,903] Trial 79 finished with value: 0.09057089919272532 and parameters: {'alpha': 0.0014075497806364688}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,906] Trial 80 finished with value: 0.09057864160384341 and parameters: {'alpha': 0.002719873967534698}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,909] Trial 81 finished with value: 0.09057053409048665 and parameters: {'alpha': 0.0013424104286710711}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,912] Trial 82 finished with value: 0.09056909140301242 and parameters: {'alpha': 0.0010765969476211118}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,914] Trial 83 finished with value: 0.09057401847143767 and parameters: {'alpha': 0.0019485324689657356}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,917] Trial 84 finished with value: 0.09057071620085017 and parameters: {'alpha': 0.0013749041186045332}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,919] Trial 85 finished with value: 0.09056883682608374 and parameters: {'alpha': 0.0010287476653788685}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,922] Trial 86 finished with value: 0.09767705176115285 and parameters: {'alpha': 1.7555012599855717}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,928] Trial 87 finished with value: 0.09057729505284062 and parameters: {'alpha': 0.00249805836858818}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,935] Trial 88 finished with value: 0.09057359968332775 and parameters: {'alpha': 0.0018771746360860884}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,945] Trial 89 finished with value: 0.09057063464578105 and parameters: {'alpha': 0.0013603542941291527}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,950] Trial 90 finished with value: 0.09058067637428255 and parameters: {'alpha': 0.0030490865470682543}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,955] Trial 91 finished with value: 0.0905690352429225 and parameters: {'alpha': 0.0010660423324937395}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,958] Trial 92 finished with value: 0.09056890387502423 and parameters: {'alpha': 0.0010413510687575058}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,962] Trial 93 finished with value: 0.09057285724052265 and parameters: {'alpha': 0.0017504946274983495}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,965] Trial 94 finished with value: 0.0905702774030175 and parameters: {'alpha': 0.0012958741406321602}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,968] Trial 95 finished with value: 0.09057582307200804 and parameters: {'alpha': 0.002253297418690493}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,974] Trial 96 finished with value: 0.09214863806029507 and parameters: {'alpha': 0.2116427381726508}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,977] Trial 97 finished with value: 0.09058932556470926 and parameters: {'alpha': 0.004369471413900948}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,983] Trial 98 finished with value: 0.09056879850035267 and parameters: {'alpha': 0.0010215430858614082}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,989] Trial 99 finished with value: 0.09057288382074022 and parameters: {'alpha': 0.001755058355190871}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,992] Trial 100 finished with value: 0.09058312351538267 and parameters: {'alpha': 0.0034345588717821095}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,995] Trial 101 finished with value: 0.09057026777618384 and parameters: {'alpha': 0.0012941218821094723}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:01,998] Trial 102 finished with value: 0.09056882728246628 and parameters: {'alpha': 0.0010269536542840557}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:02,002] Trial 103 finished with value: 0.09057242090212729 and parameters: {'alpha': 0.0016754283007161936}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:02,005] Trial 104 finished with value: 0.09057768413177052 and parameters: {'alpha': 0.002562370466986966}. Best is trial 62 with value: 0.09056875011568877.
[I 2026-03-14 19:59:02,008] Trial 105 finished with value: 0.09056872345572392 and parameters: {'alpha': 0.0010074352042063498}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,010] Trial 106 finished with value: 0.0905706967012408 and parameters: {'alpha': 0.0013714253173810343}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,013] Trial 107 finished with value: 0.09057487149633152 and parameters: {'alpha': 0.002093166247883778}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,018] Trial 108 finished with value: 0.09093693023261107 and parameters: {'alpha': 0.04589004682737202}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,020] Trial 109 finished with value: 0.09057020185901993 and parameters: {'alpha': 0.001282123535588656}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,023] Trial 110 finished with value: 0.09057231846011224 and parameters: {'alpha': 0.001657800290152324}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,027] Trial 111 finished with value: 0.0905688754954783 and parameters: {'alpha': 0.0010360165752402596}. Best is trial 105 with value: 0.09056872345572392.
[I 2026-03-14 19:59:02,030] Trial 112 finished with value: 0.09056869088954267 and parameters: {'alpha': 0.0010013045223531006}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,033] Trial 113 finished with value: 0.09056883894267159 and parameters: {'alpha': 0.0010291455397242282}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,035] Trial 114 finished with value: 0.09057043986427171 and parameters: {'alpha': 0.0013253535742245538}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,037] Trial 115 finished with value: 0.10289904540723223 and parameters: {'alpha': 9.296254304697571}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,040] Trial 116 finished with value: 0.09057457858795699 and parameters: {'alpha': 0.0020435830932532648}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,043] Trial 117 finished with value: 0.09057936305841181 and parameters: {'alpha': 0.0028375682284506446}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,046] Trial 118 finished with value: 0.09057193701365333 and parameters: {'alpha': 0.001591964152996033}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,049] Trial 119 finished with value: 0.0940651330665939 and parameters: {'alpha': 0.5476766595711096}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,052] Trial 120 finished with value: 0.09056870861695479 and parameters: {'alpha': 0.0010046445677979181}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,054] Trial 121 finished with value: 0.09056999344559752 and parameters: {'alpha': 0.0012439779119582496}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,057] Trial 122 finished with value: 0.0905688567277554 and parameters: {'alpha': 0.001032488731938449}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,059] Trial 123 finished with value: 0.09056878819805554 and parameters: {'alpha': 0.001019606384974832}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,061] Trial 124 finished with value: 0.09057232559950913 and parameters: {'alpha': 0.001659028812954774}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,064] Trial 125 finished with value: 0.09056870052519769 and parameters: {'alpha': 0.0010031199963526638}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,066] Trial 126 finished with value: 0.09057543221590066 and parameters: {'alpha': 0.0021876769809577564}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,068] Trial 127 finished with value: 0.09057073553104783 and parameters: {'alpha': 0.0013783526808489241}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,070] Trial 128 finished with value: 0.09057338091556252 and parameters: {'alpha': 0.0018399025649187101}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,072] Trial 129 finished with value: 0.09056878492153647 and parameters: {'alpha': 0.0010189904369641047}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,075] Trial 130 finished with value: 0.09057032769574767 and parameters: {'alpha': 0.0013050042852709328}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,076] Trial 131 finished with value: 0.09056886651054727 and parameters: {'alpha': 0.0010343276501573807}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,078] Trial 132 finished with value: 0.090571659465795 and parameters: {'alpha': 0.0015429317848542506}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,081] Trial 133 finished with value: 0.0905687106916497 and parameters: {'alpha': 0.0010050354599835042}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,083] Trial 134 finished with value: 0.09057648504134731 and parameters: {'alpha': 0.002363638626768875}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,085] Trial 135 finished with value: 0.09057045156350972 and parameters: {'alpha': 0.001327471408120141}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,087] Trial 136 finished with value: 0.09057385826836213 and parameters: {'alpha': 0.0019212340625562605}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,089] Trial 137 finished with value: 0.09056876368244378 and parameters: {'alpha': 0.0010149976833891334}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,092] Trial 138 finished with value: 0.09057216200168038 and parameters: {'alpha': 0.0016308778327283875}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,095] Trial 139 finished with value: 0.09057907466066335 and parameters: {'alpha': 0.0027906611499755162}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,098] Trial 140 finished with value: 0.09057006645059845 and parameters: {'alpha': 0.0012573807034765962}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,101] Trial 141 finished with value: 0.09056876852531931 and parameters: {'alpha': 0.0010159081066052913}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,103] Trial 142 finished with value: 0.09057035671663027 and parameters: {'alpha': 0.0013102699793259595}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,105] Trial 143 finished with value: 0.0905722869633327 and parameters: {'alpha': 0.0016523804505174662}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,108] Trial 144 finished with value: 0.09056872817800155 and parameters: {'alpha': 0.0010083229908635504}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,111] Trial 145 finished with value: 0.0905701131085722 and parameters: {'alpha': 0.001265944718091128}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,113] Trial 146 finished with value: 0.09057459694462985 and parameters: {'alpha': 0.002046691372385588}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,116] Trial 147 finished with value: 0.09057129553514749 and parameters: {'alpha': 0.001478219258084262}. Best is trial 112 with value: 0.09056869088954267.
[I 2026-03-14 19:59:02,119] Trial 148 finished with value: 0.0905686858225267 and parameters: {'alpha': 0.0010003498282022078}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,121] Trial 149 finished with value: 0.09057286508859592 and parameters: {'alpha': 0.0017518421107680256}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,124] Trial 150 finished with value: 0.09056875637706108 and parameters: {'alpha': 0.0010136243196872154}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,126] Trial 151 finished with value: 0.09056875984646325 and parameters: {'alpha': 0.0010142765455970352}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,129] Trial 152 finished with value: 0.09056873679926009 and parameters: {'alpha': 0.0010099437741002636}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,131] Trial 153 finished with value: 0.09057005530682061 and parameters: {'alpha': 0.001255334885330783}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,134] Trial 154 finished with value: 0.09057120226387157 and parameters: {'alpha': 0.0014616145591768266}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,136] Trial 155 finished with value: 0.09056875781997523 and parameters: {'alpha': 0.0010138955787941685}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,138] Trial 156 finished with value: 0.09057366186456411 and parameters: {'alpha': 0.0018877691317352957}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,140] Trial 157 finished with value: 0.0905762830983543 and parameters: {'alpha': 0.0023300651955532174}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,143] Trial 158 finished with value: 0.0905702817060983 and parameters: {'alpha': 0.0012966573767535694}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,146] Trial 159 finished with value: 0.09057220062589087 and parameters: {'alpha': 0.001637523996594999}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,149] Trial 160 finished with value: 0.09056874437298174 and parameters: {'alpha': 0.0010113676107766146}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,151] Trial 161 finished with value: 0.09057002931125378 and parameters: {'alpha': 0.001250562464695291}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,154] Trial 162 finished with value: 0.09056869356691245 and parameters: {'alpha': 0.0010018089729777876}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,157] Trial 163 finished with value: 0.09057133793489051 and parameters: {'alpha': 0.0014857620151476597}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,160] Trial 164 finished with value: 0.09057010215486037 and parameters: {'alpha': 0.0012639345049826193}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,162] Trial 165 finished with value: 0.09056877637064543 and parameters: {'alpha': 0.0010173829582429377}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,165] Trial 166 finished with value: 0.10955253779268062 and parameters: {'alpha': 37.300678843972}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,168] Trial 167 finished with value: 0.09056869317121717 and parameters: {'alpha': 0.0010017344190220553}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,170] Trial 168 finished with value: 0.09057445120295976 and parameters: {'alpha': 0.0020219933211880134}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,173] Trial 169 finished with value: 0.09135221714777755 and parameters: {'alpha': 0.09868824107210598}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,176] Trial 170 finished with value: 0.09057197351399902 and parameters: {'alpha': 0.0015983262357871862}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,178] Trial 171 finished with value: 0.09056874944510689 and parameters: {'alpha': 0.0010123211490181716}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,181] Trial 172 finished with value: 0.09057009938804224 and parameters: {'alpha': 0.0012634267395112554}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,183] Trial 173 finished with value: 0.09057001935068722 and parameters: {'alpha': 0.0012487338249458572}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,186] Trial 174 finished with value: 0.09057175996243033 and parameters: {'alpha': 0.001560711919684923}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,188] Trial 175 finished with value: 0.0905697401275801 and parameters: {'alpha': 0.0011974281967032333}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,190] Trial 176 finished with value: 0.09057296074833583 and parameters: {'alpha': 0.0017682560518844826}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,192] Trial 177 finished with value: 0.09056989396910946 and parameters: {'alpha': 0.0012257143431965445}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,194] Trial 178 finished with value: 0.09056868810547102 and parameters: {'alpha': 0.0010007799662954087}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,197] Trial 179 finished with value: 0.09057746000172259 and parameters: {'alpha': 0.002525321430788544}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,199] Trial 180 finished with value: 0.09056870025438395 and parameters: {'alpha': 0.00100306897202109}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,201] Trial 181 finished with value: 0.09056885104169606 and parameters: {'alpha': 0.0010314198880920068}. Best is trial 148 with value: 0.0905686858225267.
[I 2026-03-14 19:59:02,203] Trial 182 finished with value: 0.09056873609449588 and parameters: {'alpha': 0.0010098112800365172}. Best is trial 148 with value: 0.0905686858225267.

Optimizing Ridge for Device: 11.0

[I 2026-03-14 19:59:02,711] Trial 56 finished with value: 0.01967040785533188 and parameters: {'alpha': 0.015802447144469108}. Best is trial 48 with value: 0.01964888016768004.
[I 2026-03-14 19:59:02,714] Trial 57 finished with value: 0.01968008027677113 and parameters: {'alpha': 0.4016571699085211}. Best is trial 48 with value: 0.01964888016768004.
[I 2026-03-14 19:59:02,718] Trial 58 finished with value: 0.019654233807712838 and parameters: {'alpha': 0.1942236991170673}. Best is trial 48 with value: 0.01964888016768004.
[I 2026-03-14 19:59:02,721] Trial 59 finished with value: 0.019648843959446015 and parameters: {'alpha': 0.10969377019334087}. Best is trial 59 with value: 0.019648843959446015.
[I 2026-03-14 19:59:02,725] Trial 60 finished with value: 0.019657542772400973 and parameters: {'alpha': 0.038689702175812114}. Best is trial 59 with value: 0.019648843959446015.
[I 2026-03-14 19:59:02,729] Trial 61 finished with value: 0.019648847785364784 and parameters: {'alpha': 0.10815409337411029}. Best is trial 59 with value: 0.019648843959446015.
[I 2026-03-14 19:59:02,733] Trial 62 finished with value: 0.019648843221428593 and parameters: {'alpha': 0.111966280696277}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,737] Trial 63 finished with value: 0.019663542184779354 and parameters: {'alpha': 0.27630957322983}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,742] Trial 64 finished with value: 0.01964913621651525 and parameters: {'alpha': 0.12729122399921983}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,747] Trial 65 finished with value: 0.019652127356840007 and parameters: {'alpha': 0.06074493482765095}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,751] Trial 66 finished with value: 0.019732751311066908 and parameters: {'alpha': 0.8357028235904203}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,756] Trial 67 finished with value: 0.01964921854118647 and parameters: {'alpha': 0.1294828833333162}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,760] Trial 68 finished with value: 0.019858101433429903 and parameters: {'alpha': 2.1083683777764364}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,764] Trial 69 finished with value: 0.019659238947021603 and parameters: {'alpha': 0.24067742973611164}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,769] Trial 70 finished with value: 0.019661837747308203 and parameters: {'alpha': 0.02874737675517346}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,773] Trial 71 finished with value: 0.01965231381057095 and parameters: {'alpha': 0.059645204926573644}. Best is trial 62 with value: 0.019648843221428593.
[I 2026-03-14 19:59:02,777] Trial 72 finished with value: 0.019648842415576524 and parameters: {'alpha': 0.11121856186497943}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,781] Trial 73 finished with value: 0.019653367303082262 and parameters: {'alpha': 0.18521765313752472}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,785] Trial 74 finished with value: 0.019648843302852916 and parameters: {'alpha': 0.11024332911274934}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,790] Trial 75 finished with value: 0.019694103883486174 and parameters: {'alpha': 0.507839813109184}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,794] Trial 76 finished with value: 0.019648859573815212 and parameters: {'alpha': 0.11556223349272705}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,798] Trial 77 finished with value: 0.019653975354587745 and parameters: {'alpha': 0.051298729424884656}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,802] Trial 78 finished with value: 0.019679257637483617 and parameters: {'alpha': 0.3954198988438187}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,806] Trial 79 finished with value: 0.01965181766470409 and parameters: {'alpha': 0.16848884555858798}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,811] Trial 80 finished with value: 0.019666759127953726 and parameters: {'alpha': 0.02057265287221464}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,816] Trial 81 finished with value: 0.019651032333083684 and parameters: {'alpha': 0.06829935762606752}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,820] Trial 82 finished with value: 0.01964887023826209 and parameters: {'alpha': 0.10468400696641836}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,824] Trial 83 finished with value: 0.019648931308615253 and parameters: {'alpha': 0.1202920938198849}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,828] Trial 84 finished with value: 0.019661355101533832 and parameters: {'alpha': 0.2586450861287646}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,832] Trial 85 finished with value: 0.019659356885521957 and parameters: {'alpha': 0.03403507256005815}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,836] Trial 86 finished with value: 0.01965474809740325 and parameters: {'alpha': 0.19942123745131027}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,839] Trial 87 finished with value: 0.01964884528225762 and parameters: {'alpha': 0.1129307702276553}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,843] Trial 88 finished with value: 0.019650807383148037 and parameters: {'alpha': 0.07024202672548199}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,847] Trial 89 finished with value: 0.019654819021200972 and parameters: {'alpha': 0.04772681228191307}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,851] Trial 90 finished with value: 0.019649104409594758 and parameters: {'alpha': 0.1263958934240429}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,854] Trial 91 finished with value: 0.019648847346035166 and parameters: {'alpha': 0.1135832796596551}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,858] Trial 92 finished with value: 0.019651987958948992 and parameters: {'alpha': 0.1704534015374242}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,861] Trial 93 finished with value: 0.019650439331085526 and parameters: {'alpha': 0.07367554506409169}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,865] Trial 94 finished with value: 0.01964885526500729 and parameters: {'alpha': 0.10659915823741613}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,869] Trial 95 finished with value: 0.020675243282718036 and parameters: {'alpha': 7.938276553319338}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,873] Trial 96 finished with value: 0.019658756409793268 and parameters: {'alpha': 0.23646927885269758}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,876] Trial 97 finished with value: 0.0196502280188753 and parameters: {'alpha': 0.14758909387646268}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,880] Trial 98 finished with value: 0.019672988596893825 and parameters: {'alpha': 0.347949955126376}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,884] Trial 99 finished with value: 0.0196601725143815 and parameters: {'alpha': 0.032185700114853485}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,887] Trial 100 finished with value: 0.01964884242872248 and parameters: {'alpha': 0.11125510768263558}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,892] Trial 101 finished with value: 0.019648861825062848 and parameters: {'alpha': 0.11579795615601236}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,895] Trial 102 finished with value: 0.01965075012623837 and parameters: {'alpha': 0.07076093126119198}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,899] Trial 103 finished with value: 0.019648854247282733 and parameters: {'alpha': 0.11488155939565627}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,903] Trial 104 finished with value: 0.019656636943909882 and parameters: {'alpha': 0.21737060813139158}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,906] Trial 105 finished with value: 0.019651274852970125 and parameters: {'alpha': 0.1618065117103027}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,910] Trial 106 finished with value: 0.019655365912184787 and parameters: {'alpha': 0.04565524580077589}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,914] Trial 107 finished with value: 0.01966463958589369 and parameters: {'alpha': 0.2848602852128899}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,918] Trial 108 finished with value: 0.019649722201341126 and parameters: {'alpha': 0.08247283421600102}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,922] Trial 109 finished with value: 0.01965206936953633 and parameters: {'alpha': 0.06109528362053545}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,926] Trial 110 finished with value: 0.019686412045175773 and parameters: {'alpha': 0.0013895136684247127}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,929] Trial 111 finished with value: 0.019648845671224335 and parameters: {'alpha': 0.11307385745533564}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,934] Trial 112 finished with value: 0.019650396384786294 and parameters: {'alpha': 0.1499311669814004}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,937] Trial 113 finished with value: 0.019648843445103835 and parameters: {'alpha': 0.110131596140466}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,941] Trial 114 finished with value: 0.024729680327413957 and parameters: {'alpha': 36.898735779653514}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,945] Trial 115 finished with value: 0.019649829616580634 and parameters: {'alpha': 0.08094231237140671}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,949] Trial 116 finished with value: 0.019653620032013205 and parameters: {'alpha': 0.05293459318678213}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,953] Trial 117 finished with value: 0.019654143803696282 and parameters: {'alpha': 0.19330736742429522}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,956] Trial 118 finished with value: 0.019648860644250078 and parameters: {'alpha': 0.10588656437851497}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,960] Trial 119 finished with value: 0.019650251425952885 and parameters: {'alpha': 0.14791777353569366}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,964] Trial 120 finished with value: 0.01964937025787807 and parameters: {'alpha': 0.0883793022903922}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,968] Trial 121 finished with value: 0.019648843161512004 and parameters: {'alpha': 0.1119042628564025}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,971] Trial 122 finished with value: 0.019648881273089627 and parameters: {'alpha': 0.11741479396068953}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,975] Trial 123 finished with value: 0.019651353023312626 and parameters: {'alpha': 0.06580951366905047}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,979] Trial 124 finished with value: 0.019669465235896768 and parameters: {'alpha': 0.32145054573419696}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,983] Trial 125 finished with value: 0.01965745376314059 and parameters: {'alpha': 0.22485713690466483}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,987] Trial 126 finished with value: 0.019651389935718685 and parameters: {'alpha': 0.1632790510565939}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,991] Trial 127 finished with value: 0.01965747635273173 and parameters: {'alpha': 0.038879424806856834}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,994] Trial 128 finished with value: 0.01964888254998364 and parameters: {'alpha': 0.10352996611484014}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:02,999] Trial 129 finished with value: 0.01968545913020297 and parameters: {'alpha': 0.4425262133673148}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,003] Trial 130 finished with value: 0.019649819704248724 and parameters: {'alpha': 0.08108200687299134}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,006] Trial 131 finished with value: 0.0196490914579671 and parameters: {'alpha': 0.12600892548097437}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,010] Trial 132 finished with value: 0.01964900904103647 and parameters: {'alpha': 0.12338037054884649}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,014] Trial 133 finished with value: 0.0196538879690693 and parameters: {'alpha': 0.05169272963663905}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,018] Trial 134 finished with value: 0.019652726028475575 and parameters: {'alpha': 0.17856041156988436}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,021] Trial 135 finished with value: 0.01964917822781609 and parameters: {'alpha': 0.09238575405605495}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,025] Trial 136 finished with value: 0.01965099154342383 and parameters: {'alpha': 0.06863991745601508}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,029] Trial 137 finished with value: 0.019649520742683182 and parameters: {'alpha': 0.13609959392658535}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,033] Trial 138 finished with value: 0.019648856318594383 and parameters: {'alpha': 0.10643142325727444}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,036] Trial 139 finished with value: 0.019660188024256193 and parameters: {'alpha': 0.24875592405974803}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,041] Trial 140 finished with value: 0.01965497080104637 and parameters: {'alpha': 0.2016181594130481}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,044] Trial 141 finished with value: 0.019648870279803773 and parameters: {'alpha': 0.1046795391667607}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,048] Trial 142 finished with value: 0.019650520579547772 and parameters: {'alpha': 0.0728827279206161}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,052] Trial 143 finished with value: 0.01964885783808714 and parameters: {'alpha': 0.10623065873959629}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,056] Trial 144 finished with value: 0.019651344299196676 and parameters: {'alpha': 0.16269938976311}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,060] Trial 145 finished with value: 0.0196535383678922 and parameters: {'alpha': 0.05332060500060102}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,064] Trial 146 finished with value: 0.0196493396967445 and parameters: {'alpha': 0.08897276846890556}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,068] Trial 147 finished with value: 0.019649960487953914 and parameters: {'alpha': 0.14363211786347954}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,071] Trial 148 finished with value: 0.019648954117151597 and parameters: {'alpha': 0.09922417123197609}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,076] Trial 149 finished with value: 0.019650667831549375 and parameters: {'alpha': 0.07150795453091051}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,079] Trial 150 finished with value: 0.019665908377890756 and parameters: {'alpha': 0.2945128969164866}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,083] Trial 151 finished with value: 0.019648851937972688 and parameters: {'alpha': 0.10713623975282083}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,087] Trial 152 finished with value: 0.019648911483729367 and parameters: {'alpha': 0.11924568088075799}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,091] Trial 153 finished with value: 0.019652371331117986 and parameters: {'alpha': 0.05930969600525973}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,095] Trial 154 finished with value: 0.019651088124383816 and parameters: {'alpha': 0.15933859027472755}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,099] Trial 155 finished with value: 0.01964962061659795 and parameters: {'alpha': 0.08405965636116736}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,103] Trial 156 finished with value: 0.01965457310261337 and parameters: {'alpha': 0.19765886840170896}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,107] Trial 157 finished with value: 0.019655786072197458 and parameters: {'alpha': 0.04416598782599977}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,110] Trial 158 finished with value: 0.019648855214317053 and parameters: {'alpha': 0.11502154896916997}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,114] Trial 159 finished with value: 0.019648897297602382 and parameters: {'alpha': 0.1184325315527474}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,118] Trial 160 finished with value: 0.01964958217392184 and parameters: {'alpha': 0.13729282999521106}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,122] Trial 161 finished with value: 0.019648946687172396 and parameters: {'alpha': 0.0995372430470672}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,126] Trial 162 finished with value: 0.01964970603947747 and parameters: {'alpha': 0.0827147884845443}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,130] Trial 163 finished with value: 0.01965188705118411 and parameters: {'alpha': 0.16929756444638352}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,134] Trial 164 finished with value: 0.019648858467904963 and parameters: {'alpha': 0.10615495969018643}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,138] Trial 165 finished with value: 0.01965178692855677 and parameters: {'alpha': 0.06285460771055233}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,142] Trial 166 finished with value: 0.019649100839002055 and parameters: {'alpha': 0.12628904750066386}. Best is trial 72 with value: 0.019648842415576524.
[I 2026-03-14 19:59:03,146] Trial 167 finished with value: 0.019657439709853952 and parameters: {'alpha': 0.2247305462124222}. Best is trial 72 with value: 0.019648842415576524.

Optimizing Ridge for Device: 7.0

[I 2026-03-14 19:59:03,928] Trial 141 finished with value: 0.00878698395176095 and parameters: {'alpha': 0.011632904105297043}. Best is trial 89 with value: 0.008786905404588303.
[I 2026-03-14 19:59:03,929] Trial 142 finished with value: 0.008786903751214836 and parameters: {'alpha': 0.012621599763420126}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,931] Trial 143 finished with value: 0.00878864645147272 and parameters: {'alpha': 0.008834118551016977}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,933] Trial 144 finished with value: 0.008787526981224073 and parameters: {'alpha': 0.014648693443229128}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,934] Trial 145 finished with value: 0.008786945115645812 and parameters: {'alpha': 0.012937347962402384}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,936] Trial 146 finished with value: 0.008797417660320436 and parameters: {'alpha': 0.026349087093568348}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,937] Trial 147 finished with value: 0.0087884718609589 and parameters: {'alpha': 0.01624926871512537}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,939] Trial 148 finished with value: 0.008797208012241738 and parameters: {'alpha': 0.004816531626595776}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,940] Trial 149 finished with value: 0.008789921618862922 and parameters: {'alpha': 0.007766662921918702}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,941] Trial 150 finished with value: 0.00879270158659781 and parameters: {'alpha': 0.0213259803769817}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,943] Trial 151 finished with value: 0.008787093156945296 and parameters: {'alpha': 0.013524756988325518}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,944] Trial 152 finished with value: 0.008787979083149476 and parameters: {'alpha': 0.009598469391276452}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,945] Trial 153 finished with value: 0.008786959519196705 and parameters: {'alpha': 0.013011221174680584}. Best is trial 142 with value: 0.008786903751214836.
[I 2026-03-14 19:59:03,947] Trial 154 finished with value: 0.008786900407145378 and parameters: {'alpha': 0.0123871357973555}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,948] Trial 155 finished with value: 0.00879032439952336 and parameters: {'alpha': 0.018683042608768633}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,950] Trial 156 finished with value: 0.008787574808818347 and parameters: {'alpha': 0.010192482907958784}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,951] Trial 157 finished with value: 0.008792177908680381 and parameters: {'alpha': 0.006505549071539418}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,952] Trial 158 finished with value: 0.008787678144165893 and parameters: {'alpha': 0.014949203050832716}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,954] Trial 159 finished with value: 0.008809399127184571 and parameters: {'alpha': 0.038525856323637954}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,955] Trial 160 finished with value: 0.008788803498053973 and parameters: {'alpha': 0.008676691899087732}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,957] Trial 161 finished with value: 0.008786905412764343 and parameters: {'alpha': 0.012136470870120309}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,958] Trial 162 finished with value: 0.008786900505545633 and parameters: {'alpha': 0.012368294166508616}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,960] Trial 163 finished with value: 0.008786905763837881 and parameters: {'alpha': 0.012129173175944578}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,961] Trial 164 finished with value: 0.00878918506116053 and parameters: {'alpha': 0.017265072208961927}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,963] Trial 165 finished with value: 0.008786902558957593 and parameters: {'alpha': 0.012256328094609926}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,964] Trial 166 finished with value: 0.00879375389816745 and parameters: {'alpha': 0.022462553636965536}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,966] Trial 167 finished with value: 0.008789894513580861 and parameters: {'alpha': 0.0077856091434999955}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,967] Trial 168 finished with value: 0.008787487375994702 and parameters: {'alpha': 0.010352696847422236}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,969] Trial 169 finished with value: 0.008788253227930296 and parameters: {'alpha': 0.015918819003494695}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,970] Trial 170 finished with value: 0.008798727167899546 and parameters: {'alpha': 0.027698259061989527}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,971] Trial 171 finished with value: 0.008787018373638216 and parameters: {'alpha': 0.011515957942163674}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,973] Trial 172 finished with value: 0.008787062041897421 and parameters: {'alpha': 0.013421753070410224}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,975] Trial 173 finished with value: 0.008789133346503712 and parameters: {'alpha': 0.008372662981621133}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,976] Trial 174 finished with value: 0.008786993806124391 and parameters: {'alpha': 0.013171711981253742}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,978] Trial 175 finished with value: 0.008792417759792556 and parameters: {'alpha': 0.021014856368182337}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,979] Trial 176 finished with value: 0.00879393473695626 and parameters: {'alpha': 0.005818920690113098}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,981] Trial 177 finished with value: 0.008787649099761955 and parameters: {'alpha': 0.010065996614275916}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,982] Trial 178 finished with value: 0.008994649443864073 and parameters: {'alpha': 0.4624003206733902}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,984] Trial 179 finished with value: 0.008788770811026686 and parameters: {'alpha': 0.01669262161657734}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,985] Trial 180 finished with value: 0.008786948004673832 and parameters: {'alpha': 0.012952118093971024}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,987] Trial 181 finished with value: 0.008786980637636313 and parameters: {'alpha': 0.013115704920597304}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,988] Trial 182 finished with value: 0.008787426293309942 and parameters: {'alpha': 0.010474697647490849}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,990] Trial 183 finished with value: 0.008790447761937163 and parameters: {'alpha': 0.018828660641013715}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,991] Trial 184 finished with value: 0.008789709541027133 and parameters: {'alpha': 0.007919047864081936}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,992] Trial 185 finished with value: 0.008787122928949374 and parameters: {'alpha': 0.013621650536742348}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,994] Trial 186 finished with value: 0.008787763752887123 and parameters: {'alpha': 0.009893896353880695}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,995] Trial 187 finished with value: 0.008788288076556398 and parameters: {'alpha': 0.015971906639877964}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,997] Trial 188 finished with value: 0.008791013818583729 and parameters: {'alpha': 0.007094270698976863}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,998] Trial 189 finished with value: 0.009314621845663007 and parameters: {'alpha': 1.0224842220592398}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:03,999] Trial 190 finished with value: 0.00878690541258781 and parameters: {'alpha': 0.012136474537792253}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,001] Trial 191 finished with value: 0.008787049464705383 and parameters: {'alpha': 0.011413252360712042}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,002] Trial 192 finished with value: 0.008786906209227738 and parameters: {'alpha': 0.01266866631101812}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,004] Trial 193 finished with value: 0.00879074869807152 and parameters: {'alpha': 0.019176235306072677}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,005] Trial 194 finished with value: 0.008788455568053494 and parameters: {'alpha': 0.009032553669370082}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,007] Trial 195 finished with value: 0.008787860200121953 and parameters: {'alpha': 0.015286521227728491}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,008] Trial 196 finished with value: 0.008796425380552966 and parameters: {'alpha': 0.025304195827838813}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,010] Trial 197 finished with value: 0.008786939716888405 and parameters: {'alpha': 0.011814559239384953}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,011] Trial 198 finished with value: 0.00878743518243669 and parameters: {'alpha': 0.010456757679797214}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,013] Trial 199 finished with value: 0.008791044361892424 and parameters: {'alpha': 0.0070771115559895995}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,015] Trial 200 finished with value: 0.008786900503665694 and parameters: {'alpha': 0.01236866029389168}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,017] Trial 201 finished with value: 0.008786902026133605 and parameters: {'alpha': 0.012281479028872718}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,018] Trial 202 finished with value: 0.008786912462380645 and parameters: {'alpha': 0.012028939020653289}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,020] Trial 203 finished with value: 0.00878911290921116 and parameters: {'alpha': 0.008390898089485253}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,021] Trial 204 finished with value: 0.008789358656947516 and parameters: {'alpha': 0.017489807371809316}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,023] Trial 205 finished with value: 0.008787603838396881 and parameters: {'alpha': 0.01014185076579449}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,024] Trial 206 finished with value: 0.008787884506320185 and parameters: {'alpha': 0.015328274417713275}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,026] Trial 207 finished with value: 0.008787063474661573 and parameters: {'alpha': 0.011368099973212429}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,027] Trial 208 finished with value: 0.00879346511007101 and parameters: {'alpha': 0.00599097039189471}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,029] Trial 209 finished with value: 0.008788305536896114 and parameters: {'alpha': 0.009198085478982605}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,030] Trial 210 finished with value: 0.008791837913920636 and parameters: {'alpha': 0.020384460259529034}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,032] Trial 211 finished with value: 0.008786900936851314 and parameters: {'alpha': 0.012476572228436752}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,033] Trial 212 finished with value: 0.008786900648592985 and parameters: {'alpha': 0.012346956464539063}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,035] Trial 213 finished with value: 0.008786932670055762 and parameters: {'alpha': 0.011850260201313714}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,036] Trial 214 finished with value: 0.008788994952973484 and parameters: {'alpha': 0.008497098997956969}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,038] Trial 215 finished with value: 0.008788444540937143 and parameters: {'alpha': 0.01620863835159942}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,039] Trial 216 finished with value: 0.008787119073007596 and parameters: {'alpha': 0.011196431856633935}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,041] Trial 217 finished with value: 0.008787522646063691 and parameters: {'alpha': 0.014639791864349804}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,043] Trial 218 finished with value: 0.008787269789318963 and parameters: {'alpha': 0.010803183000507076}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,044] Trial 219 finished with value: 0.008790033616769258 and parameters: {'alpha': 0.007689268640854985}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,046] Trial 220 finished with value: 0.00879103402894794 and parameters: {'alpha': 0.019499068625958592}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,047] Trial 221 finished with value: 0.008786900799928438 and parameters: {'alpha': 0.012459043281818285}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,049] Trial 222 finished with value: 0.008786909005173777 and parameters: {'alpha': 0.012710712482207684}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,051] Trial 223 finished with value: 0.00878734627885424 and parameters: {'alpha': 0.014249315738836518}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,052] Trial 224 finished with value: 0.008787949007541563 and parameters: {'alpha': 0.009639056603632292}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,053] Trial 225 finished with value: 0.008788650216443294 and parameters: {'alpha': 0.016514114547574423}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,055] Trial 226 finished with value: 0.008786901105181136 and parameters: {'alpha': 0.01249846528220321}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,057] Trial 227 finished with value: 0.008786945326229928 and parameters: {'alpha': 0.012938423776791589}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,059] Trial 228 finished with value: 0.008794545541884902 and parameters: {'alpha': 0.023321620521669452}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,060] Trial 229 finished with value: 0.008788711421156798 and parameters: {'alpha': 0.008768336340188561}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,062] Trial 230 finished with value: 0.008788197424618591 and parameters: {'alpha': 0.0158331232212094}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,063] Trial 231 finished with value: 0.008787089023747233 and parameters: {'alpha': 0.01128862367664419}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,065] Trial 232 finished with value: 0.00878695367498148 and parameters: {'alpha': 0.01298117615054802}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,067] Trial 233 finished with value: 0.00878769765656475 and parameters: {'alpha': 0.00998977512232393}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,068] Trial 234 finished with value: 0.008786913610082717 and parameters: {'alpha': 0.01201365637091307}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,070] Trial 235 finished with value: 0.008790625018690433 and parameters: {'alpha': 0.01903481325110299}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,071] Trial 236 finished with value: 0.008787471839230105 and parameters: {'alpha': 0.014533493649482247}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,073] Trial 237 finished with value: 0.008790917897328332 and parameters: {'alpha': 0.0071484669207394855}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,074] Trial 238 finished with value: 0.008786973824832978 and parameters: {'alpha': 0.011669916437802042}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,076] Trial 239 finished with value: 0.008788210815047165 and parameters: {'alpha': 0.009307455441473001}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,077] Trial 240 finished with value: 0.008788071307168436 and parameters: {'alpha': 0.01563659200776427}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,078] Trial 241 finished with value: 0.008786920938420673 and parameters: {'alpha': 0.011924963875320839}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,080] Trial 242 finished with value: 0.008786952793145092 and parameters: {'alpha': 0.011754488257922809}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,081] Trial 243 finished with value: 0.008787241499145167 and parameters: {'alpha': 0.013973543159598442}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,083] Trial 244 finished with value: 0.008788439090193546 and parameters: {'alpha': 0.009050442908200071}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,084] Trial 245 finished with value: 0.008787497245496618 and parameters: {'alpha': 0.010333723103085125}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,086] Trial 246 finished with value: 0.008823135418583572 and parameters: {'alpha': 0.0010418097877960182}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,087] Trial 247 finished with value: 0.008790207225880572 and parameters: {'alpha': 0.01854365058208622}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,089] Trial 248 finished with value: 0.008786920441619524 and parameters: {'alpha': 0.011930303919880704}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,090] Trial 249 finished with value: 0.008791149311296603 and parameters: {'alpha': 0.00701835207860533}. Best is trial 154 with value: 0.008786900407145378.
[I 2026-03-14 19:59:04,092] Trial 250 finished with value: 0.008787652154197767 and parameters: {'alpha': 0.014898382902584375}. Best is trial 154 with value: 0.008786900407145378.

Best Ridge Alphas found: {np.float64(19.0): 0.001000029674436957, np.float64(11.0): 0.11121856186497943, np.float64(7.0): 0.0123871357973555}

In [115]:
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error

train_comparison = []

# Get the list of device types that have both models
device_types = set(lasso_models.keys()).intersection(set(ridge_models.keys()))

for d_type in device_types:
    # Filter train data for this device type
    train_subset = daily_train[daily_train['deviceType'] == d_type].dropna(subset=feature_cols_present + [TARGET_COL])

    if len(train_subset) == 0:
        continue

    X_t = train_subset[feature_cols_present].values
    y_t = train_subset[TARGET_COL].values

    # Lasso In-Sample Metrics
    l_pred = lasso_models[d_type].predict(X_t)
    l_mae = mean_absolute_error(y_t, l_pred)
    l_mse = mean_squared_error(y_t, l_pred)

    # Ridge In-Sample Metrics
    r_pred = ridge_models[d_type].predict(X_t)
    r_mae = mean_absolute_error(y_t, r_pred)
    r_mse = mean_squared_error(y_t, r_pred)

    # Track who wins on training data
    best_mae = "Lasso" if l_mae < r_mae else "Ridge"

    train_comparison.append({
        'DeviceType': d_type,
        'Samples': len(train_subset),
        'Lasso_MAE': l_mae,
        'Ridge_MAE': r_mae,
        'Lasso_MSE': l_mse,
        'Ridge_MSE': r_mse,
        'Best_Train_Model': best_mae
    })

# Create DataFrame
train_comp_df = pd.DataFrame(train_comparison)

# Style to highlight the lower error in each row
def highlight_min(s):
    is_min = s == s.min()
    return ['background-color: #e3f2fd' if v else '' for v in is_min]

print("In-Sample Training Comparison (Lasso vs Ridge) per Device Type:")
display(train_comp_df.style.apply(highlight_min, subset=['Lasso_MAE', 'Ridge_MAE'], axis=1)
                    .format(precision=6))

# Tally the results
print(f"\nTraining Set Winners (MAE):")
print(train_comp_df['Best_Train_Model'].value_counts())

In-Sample Training Comparison (Lasso vs Ridge) per Device Type:

Training Set Winners (MAE):
Best_Train_Model
Ridge    3
Name: count, dtype: int64

In [110]:
comparison_rows = []
for d_type in lasso_models.keys():
    lasso_coefs = lasso_models[d_type].coef_
    # Count how many features Lasso kept (non-zero)
    active_features = sum(lasso_coefs != 0)

    comparison_rows.append({
        'DeviceType': d_type,
        'Lasso_Alpha': lasso_best_alphas[d_type],
        'Ridge_Alpha': ridge_best_alphas[d_type],
        'Features_Kept_By_Lasso': active_features
    })

comparison_df = pd.DataFrame(comparison_rows)
display(comparison_df)

   DeviceType  Lasso_Alpha  Ridge_Alpha  Features_Kept_By_Lasso
0        19.0      0.00001     0.001000                      10
1        11.0      0.00001     0.111219                      10
2         7.0      0.00001     0.012387                       6

In [90]:
deletion_report = []

for d_type, model in lasso_models.items():
    # Identify which features have a 0 coefficient
    # We use a small tolerance (1e-10) just in case of tiny numerical noise
    zero_features = [
        feat for feat, coef in zip(feature_cols_present, model.coef_)
        if abs(coef) < 1e-10
    ]

    # Identify which features are actually being used
    kept_features = [
        feat for feat, coef in zip(feature_cols_present, model.coef_)
        if abs(coef) >= 1e-10
    ]

    deletion_report.append({
        'DeviceType': d_type,
        'Alpha': lasso_best_alphas[d_type],
        'Total_Features': len(feature_cols_present),
        'Kept_Count': len(kept_features),
        'Deleted_Count': len(zero_features),
        'Features_To_Delete': ", ".join(zero_features) if zero_features else "None"
    })

# Convert to DataFrame for a clean view
deletion_df = pd.DataFrame(deletion_report)
display(deletion_df)

,DeviceType,Alpha,Total_Features,Kept_Count,Deleted_Count,Features_To_Delete
0,19.0,0.00001,16,10,6,"t3, t9, t12, t13, x1, deviceType"
1,11.0,0.00001,16,10,6,"t2, t11, t12, t13, x1, deviceType"
2,7.0,0.00001,16,6,10,"t2, t3, t5, t7, t10, t11, t12, t13, x1, device..."

## Cell 5 — Chunked load & daily aggregation (valid + test)

In [5]:
pred_sums = []
pred_counts = []

for i, chunk in enumerate(pd.read_csv(DATA_PATH, chunksize=CHUNK_SIZE, low_memory=False)):
    # Filter valid + test only
    chunk = chunk[chunk["period"].isin(["valid", "test"])].copy()
    if len(chunk) == 0:
        continue

    chunk["timedate"] = pd.to_datetime(
        chunk["timedate"].str.replace(" UTC", "", regex=False), utc=True
    )
    chunk["date"] = chunk["timedate"].dt.date

    cols_present = [c for c in feature_cols_present if c in chunk.columns]
    grp = chunk.groupby(["deviceId", "date"])[cols_present]

    pred_sums.append(grp.sum())
    pred_counts.append(grp.count())

    if (i + 1) % 5 == 0:
        print(f"  processed {(i + 1) * CHUNK_SIZE:,} rows...")

print("Combining partial aggregations...")
total_sum = pd.concat(pred_sums).groupby(level=["deviceId", "date"]).sum()
total_count = pd.concat(pred_counts).groupby(level=["deviceId", "date"]).sum()
daily_pred_df = (total_sum / total_count).reset_index()

del pred_sums, pred_counts, total_sum, total_count

print(f"Daily valid+test aggregation complete: {daily_pred_df.shape}")

  processed 2,500,000 rows...
  processed 5,000,000 rows...
  processed 7,500,000 rows...
  processed 10,000,000 rows...
  processed 12,500,000 rows...
  processed 15,000,000 rows...
  processed 17,500,000 rows...
  processed 20,000,000 rows...
  processed 22,500,000 rows...
  processed 25,000,000 rows...
  processed 27,500,000 rows...
  processed 30,000,000 rows...
  processed 32,500,000 rows...
  processed 35,000,000 rows...
  processed 37,500,000 rows...
  processed 40,000,000 rows...
  processed 42,500,000 rows...
  processed 45,000,000 rows...
  processed 47,500,000 rows...
  processed 50,000,000 rows...
  processed 52,500,000 rows...
  processed 55,000,000 rows...
  processed 57,500,000 rows...
  processed 60,000,000 rows...
  processed 62,500,000 rows...
Combining partial aggregations...
Daily valid+test aggregation complete: (105529, 18)

## Cell 6 — Predict daily x2, aggregate to monthly

In [38]:
# pred_clean = daily_pred_df.dropna(subset=feature_cols_present).copy()
# X_pred = pred_clean[feature_cols_present].values
# pred_clean["daily_x2_pred"] = model.predict(X_pred)
#
# # Extract year/month from date
# pred_clean["date"] = pd.to_datetime(pred_clean["date"])
# pred_clean["year"] = pred_clean["date"].dt.year
# pred_clean["month"] = pred_clean["date"].dt.month
#
# # Aggregate daily predictions to monthly mean
# monthly_preds = (
#     pred_clean
#     .groupby(["deviceId", "year", "month"])["daily_x2_pred"]
#     .mean()
#     .reset_index()
#     .rename(columns={"daily_x2_pred": "prediction"})
# )
#
# print(f"Monthly predictions shape: {monthly_preds.shape}")
# print(f"Year/month range:")
# print(monthly_preds[["year", "month"]].drop_duplicates().sort_values(["year", "month"]).to_string(index=False))
# monthly_preds.head()

Monthly predictions shape: (3559, 4)
Year/month range:
 year  month
 2025      5
 2025      6
 2025      7
 2025      8
 2025      9
 2025     10

                                            deviceId  year  month  prediction
0  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      5    0.225626
1  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      6    0.164666
2  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      7    0.165904
3  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      8    0.163678
4  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      9    0.199846

# normal regression

In [116]:
# 1. Prepare the dataframe
pred_clean = daily_pred_df.dropna(subset=feature_cols_present).copy()
pred_clean["daily_x2_pred"] = 0.0  # Initialize prediction column

# 2. Apply the correct model for each device type
# We use the 'models_per_type' dictionary created in the previous step

#                   CHANGE MODEL DICT HERE
for d_type, model in ridge_models.items():
    # Find rows matching this device type
    mask = pred_clean["deviceType"] == d_type

    if mask.any():
        X_pred = pred_clean.loc[mask, feature_cols_present].values
        pred_clean.loc[mask, "daily_x2_pred"] = model.predict(X_pred)

# 3. Extract year/month from date
pred_clean["date"] = pd.to_datetime(pred_clean["date"])
pred_clean["year"] = pred_clean["date"].dt.year
pred_clean["month"] = pred_clean["date"].dt.month

# 4. Aggregate daily predictions to monthly mean (as required by the challenge)
monthly_preds = (
    pred_clean
    .groupby(["deviceId", "year", "month"])["daily_x2_pred"]
    .mean()
    .reset_index()
    .rename(columns={"daily_x2_pred": "prediction"})
)

# Summary output
print(f"Monthly predictions shape: {monthly_preds.shape}")
print(f"Year/month range:")
print(monthly_preds[["year", "month"]].drop_duplicates().sort_values(["year", "month"]).to_string(index=False))
monthly_preds.head()

Monthly predictions shape: (3559, 4)
Year/month range:
 year  month
 2025      5
 2025      6
 2025      7
 2025      8
 2025      9
 2025     10

                                            deviceId  year  month  prediction
0  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      5    0.109795
1  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      6    0.033200
2  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      7    0.021546
3  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      8    0.020250
4  000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc...  2025      9    0.087769

## Cell 7 — Generate submission CSV

In [117]:
# Filter to May-Oct 2025 only
submission = monthly_preds[
    (monthly_preds["year"] == 2025) & (monthly_preds["month"].between(5, 10))
].copy()

submission = submission[["deviceId", "year", "month", "prediction"]]

print(f"Submission shape: {submission.shape}")
print(f"Expected: 600 devices × 6 months = 3600 rows")
print(f"Unique devices: {submission['deviceId'].nunique()}")
print(f"Months covered: {sorted(submission['month'].unique())}")
print(f"\nSample:")
print(submission.head(12).to_string(index=False))

OUT_PATH = "data/different_device_ridge_optuna.csv"
submission.to_csv(OUT_PATH, index=False)
print(f"\nSaved → {OUT_PATH}")

Submission shape: (3559, 4)
Expected: 600 devices × 6 months = 3600 rows
Unique devices: 600
Months covered: [np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10)]

Sample:
                                                        deviceId  year  month  prediction
000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc93ae46eecc5798f0fe  2025      5    0.109795
000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc93ae46eecc5798f0fe  2025      6    0.033200
000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc93ae46eecc5798f0fe  2025      7    0.021546
000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc93ae46eecc5798f0fe  2025      8    0.020250
000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc93ae46eecc5798f0fe  2025      9    0.087769
000cc3cb7f030c3d0c481bd0e7cf42ee283012c3cb5bfc93ae46eecc5798f0fe  2025     10    0.190097
005767201ec5d7c3336b3b4d1ffa8a72e7ca1ecdaac30fe5a99d7a76b53f9fc9  2025      5    0.049194
005767201ec5d7c3336b3b4d1ffa8a72e7ca1ecdaac30fe5a99d7a76b53f9fc9  2025      6    0.010300
005767201ec5d7c3336b3b4d1ffa8a72e7ca1ecdaac30fe5a99d7a76b53f9fc9  2025      7    0.009422
005767201ec5d7c3336b3b4d1ffa8a72e7ca1ecdaac30fe5a99d7a76b53f9fc9  2025      8    0.015012
005767201ec5d7c3336b3b4d1ffa8a72e7ca1ecdaac30fe5a99d7a76b53f9fc9  2025      9    0.033955
005767201ec5d7c3336b3b4d1ffa8a72e7ca1ecdaac30fe5a99d7a76b53f9fc9  2025     10    0.097553

Saved → data/different_device_ridge_optuna.csv